// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.Helpers;
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class AdvanceAdjustmentDetailModel
    {
        public int AdvanceAdjustmentDetId { get; set; }

        public int? AdvanceAdjustmentId { get; set; }

        [Display(Name = "Amount FC")]
        [Required(ErrorMessage = "Amount FC is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? AmountFc { get; set; }

        [Display(Name = "Amount")]
        [Required(ErrorMessage = "Amount is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? Amount { get; set; }

        [Display(Name = "Narration")]
        [Required(ErrorMessage = "Narration is required.")]
        public string Narration { get; set; }
        
        [Display(Name = "Sales Invoice")]
        //[Required(ErrorMessage = "Sales Invoice is required.")]
        public int? SalesInvoiceId { get; set; }

        [Display(Name = "Purchase Invoice")]
        //[Required(ErrorMessage = "Purchase Invoice is required.")]
        public int? PurchaseInvoiceId { get; set; }

        [Display(Name = "Credit Note")]
        //[Required(ErrorMessage = "Credit Note is required.")]
        public int? CreditNoteId { get; set; }

        [Display(Name = "Debit Note")]
        //[Required(ErrorMessage = "Debit Note is required.")]
        public int? DebitNoteId { get; set; }

    }
}