// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.Helpers;
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class AdvanceAdjustmentModel
    {
        public int AdvanceAdjustmentId { get; set; }

        [Display(Name = "Advance Adjustment No")]
        [Required(ErrorMessage = "Vocuher No is required.")]
        public string AdvanceAdjustmentNo { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Advance Adjustment Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Advance Adjustment Date is required.")]
        public DateTime? AdvanceAdjustmentDate { get; set; }

        [Display(Name = "Account Ledger")]
        [Required(ErrorMessage = "Account Ledger is required.")]
        public int? AccountLedgerId { get; set; }

        [Display(Name = "Payment Voucher")]
        [Required(ErrorMessage = "Payment Voucher is required.")]
        public int? PaymentVoucherId { get; set; }

        [Display(Name = "Receipt Voucher")]
        [Required(ErrorMessage = "Receipt Voucher is required.")]
        public int? ReceiptVoucherId { get; set; }

        [Display(Name = "Narration")]
        [StringLength(2000, ErrorMessage = "Narration cannot exceed 2000 characters.")]
        public string Narration { get; set; }

        [Display(Name = "Currency")]
        [Required(ErrorMessage = "Currency is required.")]
        public int CurrencyId { get; set; }

        [Display(Name = "Exchange Rate")]
        [Required(ErrorMessage = "Exchange Rate is required.")]
        public decimal ExchangeRate { get; set; }

        [Display(Name = "Amount FC")]
        [Required(ErrorMessage = "Amount FC is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? AmountFc { get; set; }

        [Display(Name = "Amount")]
        [Required(ErrorMessage = "Amount is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? Amount { get; set; }

        [Display(Name = "Amount FC in word")]
        [Required(ErrorMessage = "Amount FC in word is required.")]
        public string AmountFcinWord { get; set; }

        public int? StatusId { get; set; }

        public int CompanyId { get; set; }

        public int FinancialYearId { get; set; }

        public int? MaxNo { get; set; }

        public int? VoucherStyleId { get; set; }

        //####

        public string StatusName { get; set; }
        public string PreparedByName { get; set; }

    }
}