// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.Helpers;
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class ContraVoucherDetailModel
    {
        public int ContraVoucherDetId { get; set; }

        public int? ContraVoucherId { get; set; }

        [Display(Name = "Particular")]
        [Required(ErrorMessage = "Particular is required.")]
        public int? ParticularLedgerId { get; set; }

        [Display(Name = "Narration")]
        [Required(ErrorMessage = "Narration is required.")]
        public string Narration { get; set; }
        
        [Display(Name = "Debit Amount FC")]
        [Required(ErrorMessage = "Debit Amount FC is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? DebitAmountFc { get; set; }

        [Display(Name = "Debit Amount")]
        [Required(ErrorMessage = "Debit Amount is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? DebitAmount { get; set; }

        [Display(Name = "Credit Amount FC")]
        [Required(ErrorMessage = "Credit Amount FC is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? CreditAmountFc { get; set; }

        [Display(Name = "Credit Amount")]
        [Required(ErrorMessage = "Credit Amount is required.")]
        //[RegularExpression(RegexHelper.DecimalOnly, ErrorMessage = "Numbers only.")]
        public decimal? CreditAmount { get; set; }

    }
}