// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class JournalRegisterModel
    {
        public int SequenceNo { get; set; }
        public int SrNo { get; set; }
        public int DocumentDetId { get; set; }
        public int DocumentId { get; set; }
        public string DocumentNo { get; set; }
        public DateTime? DocumentDate { get; set; }

        //[Display(Name = "Cheque No")]
        //public string ChequeNo { get; set; }

        //[Display(Name = "Cheque Date")]
        //public DateTime? ChequeDate { get; set; }

        //[Display(Name = "Bank Name")]
        //public string BankName { get; set; }

        public int? CurrencyId { get; set; }

        [Display(Name = "Currency Code")]
        public string CurrencyCode { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.000000}", ApplyFormatInEditMode = true)]
        [Display(Name = "Exchange Rate")]
        public decimal? ExchangeRate { get; set; }

        [Display(Name = "Particular")]
        public string ParticularLedgerName { get; set; }

        [Display(Name = "Narration")]
        public string Narration { get; set; }
        public int? PurchaseInvoiceId { get; set; }

        public int? SalesInvoiceId { get; set; }

        public int? CreditNoteId { get; set; }

        public int? DebitNoteId { get; set; }

        [Display(Name = "Invoice Type")]
        public string InvoiceType { get; set; }

        [Display(Name = "Invoice No")]
        public string InvoiceNo { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal CreditAmount_FC { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DebitAmount_FC { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal CreditAmount { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DebitAmount { get; set; }

    }
}