// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.Helpers;
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class JournalVoucherDetailModel
    {
        public int JournalVoucherDetId { get; set; }

        public int JournalVoucherId { get; set; }

        [Display(Name = "Particular")]
        [Required(ErrorMessage = "Particular is required.")]
        public int ParticularLedgerId { get; set; }

        [Display(Name = "Transaction Type")]
        [Required(ErrorMessage = "Transaction Type is required.")]
        public int TransactionTypeId { get; set; }

        [Display(Name = "Narration")]
        public string Narration { get; set; }

        [Display(Name = "Sales Invoice")]
        public int? SalesInvoiceId { get; set; }

        [Display(Name = "Purchase Invoice")]
        public int? PurchaseInvoiceId { get; set; }

        [Display(Name = "Credit Note")]
        public int? CreditNoteId { get; set; }

        [Display(Name = "Debit Note")]
        public int? DebitNoteId { get; set; }

        [Display(Name = "Debit Amount FC")]
        [Required(ErrorMessage = "Debit Amount FC is required.")]
        [RegularExpression(RegexHelper.Decimal4Digit, ErrorMessage = "Decimal only.")]
        public decimal DebitAmountFc { get; set; }

        [Display(Name = "Debit Amount")]
        [RegularExpression(RegexHelper.Decimal4Digit, ErrorMessage = "Decimal only.")]
        public decimal DebitAmount { get; set; }

        [Display(Name = "Credit Amount FC")]
        [Required(ErrorMessage = "Credit Amount FC is required.")]
        [RegularExpression(RegexHelper.Decimal4Digit, ErrorMessage = "Decimal only.")]
        public decimal CreditAmountFc { get; set; }

        [Display(Name = "Credit Amount")]
        [RegularExpression(RegexHelper.Decimal4Digit, ErrorMessage = "Decimal only.")]
        public decimal CreditAmount { get; set; }

        //###

        public string TransactionTypeName { get; set; }

        public string ParticularLedgerName { get; set; }

        public string InvoiceType { get; set; }

        public string InvoiceNo { get; set; }

    }
}