// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.Helpers;
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class JournalVoucherModel
    {
        public int JournalVoucherId { get; set; }

        [Display(Name = "Voucher No")]
        [Required(ErrorMessage = "Vocuher No is required.")]
        public string VoucherNo { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Voucher Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Voucher Date is required.")]
        public DateTime? VoucherDate { get; set; }

        [Display(Name = "Currency")]
        [Required(ErrorMessage = "Currency is required.")]
        public int CurrencyId { get; set; }

        [Display(Name = "Exchange Rate")]
        [Required(ErrorMessage = "Exchange Rate is required.")]
        [RegularExpression(RegexHelper.Decimal6Digit, ErrorMessage = RegexHelper.Decimal6DigitMessage)]
        [Range(0.000001, Double.MaxValue, ErrorMessage = "Value must be greater than 0.")]
        [DisplayFormat(DataFormatString = "{0:0.000000}", ApplyFormatInEditMode = true)]
        public decimal ExchangeRate { get; set; }

        [Display(Name = "Narration")]
        [StringLength(2000, ErrorMessage = "Narration cannot exceed 2000 characters.")]
        public string Narration { get; set; }

        [Display(Name = "Amount FC")]
        [Required(ErrorMessage = "Amount FC is required.")]
        [RegularExpression(RegexHelper.Decimal2Digit, ErrorMessage = RegexHelper.Decimal2DigitMessage)]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal AmountFc { get; set; }

        [Display(Name = "Amount FC In word")]
        public string AmountFcInWord { get; set; }

        [Display(Name = "Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal Amount { get; set; }

        [Display(Name = "Debit Amount FC")]
        [RegularExpression(RegexHelper.Decimal2Digit, ErrorMessage = RegexHelper.Decimal2DigitMessage)]
        public decimal DebitAmountFc { get; set; }

        [Display(Name = "Debit Amount")]
        [RegularExpression(RegexHelper.Decimal2Digit, ErrorMessage = RegexHelper.Decimal2DigitMessage)]
        public decimal DebitAmount { get; set; }

        [Display(Name = "Credit Amount FC")]
        [RegularExpression(RegexHelper.Decimal2Digit, ErrorMessage = RegexHelper.Decimal2DigitMessage)]
        public decimal CreditAmountFc { get; set; }

        [Display(Name = "Credit Amount")]
        [RegularExpression(RegexHelper.Decimal2Digit, ErrorMessage = RegexHelper.Decimal2DigitMessage)]
        public decimal CreditAmount { get; set; }

        [Display(Name = "Status")]
        public int StatusId { get; set; }

        public int CompanyId { get; set; }

        public int FinancialYearId { get; set; }

        public int MaxNo { get; set; }

        public int VoucherStyleId { get; set; }

        //####

        public string CurrencyCode { get; set; }

        public string StatusName { get; set; }

        public string PreparedByName { get; set; }

        public int NoOfLineItems { get; set; }

    }
}