// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class PurchaseRegisterModel
    {
        public int SequenceNo { get; set; }
        public int SrNo { get; set; }
        public int PurchaseInvoiceId { get; set; }

        [Display(Name = "Invoice No")]
        public string InvoiceNo { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Invoice Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? InvoiceDate { get; set; }

        [Display(Name = "Supplier")]
        public int SupplierLedgerId { get; set; }

        [Display(Name = "Bill To Address")]
        public int BillToAddressId { get; set; }

        [Display(Name = "Account")]
        public int AccountLedgerId { get; set; }

        [Display(Name = "Supplier Ref No")]
        public string SupplierReferenceNo { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Supplier Ref Date")]
        public DateTime? SupplierReferenceDate { get; set; }

        [Display(Name = "Credit Limit Days")]
        public int? CreditLimitDays { get; set; }

        [Display(Name = "Payment Term")]
        public string PaymentTerm { get; set; }

        [Display(Name = "Remark")]
        public string Remark { get; set; }

        [Display(Name = "Tax Model Type")]
        public string TaxModelType { get; set; }

        [Display(Name = "Tax Register")]
        public int TaxRegisterId { get; set; }

        [Display(Name = "Currency")]
        public int CurrencyId { get; set; }

        [Display(Name = "Exchange Rate")]
        [Required(ErrorMessage = "Exchange Rate is required.")]
        public decimal ExchangeRate { get; set; }

        [Display(Name = "Line Total Amount FC")]
        public decimal TotalLineItemAmountFc { get; set; }

        [Display(Name = "Line Total Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal TotalLineItemAmount { get; set; }

        [Display(Name = "Gross Amount FC")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal GrossAmountFc { get; set; }

        [Display(Name = "Gross Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal GrossAmount { get; set; }

        [Display(Name = "Net Amount FC")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal NetAmountFc { get; set; }

        [Display(Name = "Net Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal NetAmount { get; set; }

        [Display(Name = "Net Amount FC In Word")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public string NetAmountFcInWord { get; set; }

        [Display(Name = "Tax Amount FC")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal TaxAmountFc { get; set; }

        [Display(Name = "Tax Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal TaxAmount { get; set; }

        [Display(Name = "Discount Type")]
        [Required(ErrorMessage = "Discount Type is required.")]
        public string DiscountPercentageOrAmount { get; set; }

        [Display(Name = "Discount Per / Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DiscountPerOrAmountFc { get; set; }

        [Display(Name = "Discount Amount FC")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DiscountAmountFc { get; set; }

        [Display(Name = "Discount Amount")]
        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DiscountAmount { get; set; }

        public string SupplierLedgerName { get; set; }
        public string BillToAddress { get; set; }
        public string AccountLedgerName { get; set; }
        public string BankLedgerName { get; set; }
        public string TaxRegisterName { get; set; }
        public string CurrencyCode { get; set; }

    }
}