// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations;

namespace ERP.Models.Accounts
{
    public partial class TrialBalanceReportModel
    {
        public int SequenceNo { get; set; }

        public int SrNo { get; set; }

        public int DocumentId { get; set; }

        public string DocumentType { get; set; }

        [Display(Name = "LedgerId")]
        public int LedgerId { get; set; }

        [Display(Name = "Code")]
        public string LedgerCode { get; set; }

        [Display(Name = "Particulars")]
        public string ParticularLedgerName{ get; set; }

        [Display(Name = "Is Group")]
        public bool IsGroup { get; set; }

        [Display(Name = "G/L")]
        public string GroupOrLedger { get; set; }

        [Display(Name = "ParentGroupId")]
        public int ParentGroupId { get; set; }

        [Display(Name = "TopGroupId")]
        public int TopGroupId { get; set; }

        [Display(Name = "LevelNo")]
        public int LevelNo { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal DebitAmount { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal CreditAmount { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}", ApplyFormatInEditMode = true)]
        public decimal ClosingAmount { get; set; }

    }
}