// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("advanceadjustmentdetail")]
    public partial class Advanceadjustmentdetail
    {
        [Key]
        public int AdvanceAdjustmentDetId { get; set; }
        public int? AdvanceAdjustmentId { get; set; }
        [Column("Amount_FC", TypeName = "decimal(18,4)")]
        public decimal? AmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        public int? SalesInvoiceId { get; set; }
        public int? PurchaseInvoiceId { get; set; }
        public int? CreditNoteId { get; set; }
        public int? DebitNoteId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(AdvanceAdjustmentId))]
        [InverseProperty(nameof(Advanceadjustment.Advanceadjustmentdetails))]
        public virtual Advanceadjustment AdvanceAdjustment { get; set; }
        [ForeignKey(nameof(CreditNoteId))]
        [InverseProperty(nameof(Creditnote.Advanceadjustmentdetails))]
        public virtual Creditnote CreditNote { get; set; }
        [ForeignKey(nameof(DebitNoteId))]
        [InverseProperty(nameof(Debitnote.Advanceadjustmentdetails))]
        public virtual Debitnote DebitNote { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.AdvanceadjustmentdetailPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(PurchaseInvoiceId))]
        [InverseProperty(nameof(Purchaseinvoice.Advanceadjustmentdetails))]
        public virtual Purchaseinvoice PurchaseInvoice { get; set; }
        [ForeignKey(nameof(SalesInvoiceId))]
        [InverseProperty(nameof(Salesinvoice.Advanceadjustmentdetails))]
        public virtual Salesinvoice SalesInvoice { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.AdvanceadjustmentdetailUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}