// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("aspnetrole")]
    public partial class Aspnetrole
    {
        public Aspnetrole()
        {
            Aspnetroleclaims = new HashSet<Aspnetroleclaim>();
            Aspnetuserroles = new HashSet<Aspnetuserrole>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string Name { get; set; }
        [Column(TypeName = "varchar(256)")]
        public string NormalizedName { get; set; }
        [Column(TypeName = "longtext")]
        public string ConcurrencyStamp { get; set; }

        [InverseProperty(nameof(Aspnetroleclaim.Role))]
        public virtual ICollection<Aspnetroleclaim> Aspnetroleclaims { get; set; }
        [InverseProperty(nameof(Aspnetuserrole.Role))]
        public virtual ICollection<Aspnetuserrole> Aspnetuserroles { get; set; }
    }
}