// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("aspnetusertokens")]
    public partial class Aspnetusertoken
    {
        [Key]
        public int UserId { get; set; }
        [Key]
        [Column(TypeName = "varchar(255)")]
        public string LoginProvider { get; set; }
        [Key]
        [Column(TypeName = "varchar(255)")]
        public string Name { get; set; }
        [Column(TypeName = "longtext")]
        public string Value { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Aspnetuser.Aspnetusertokens))]
        public virtual Aspnetuser User { get; set; }
    }
}