// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Aspnetuser
    {
        public Aspnetuser()
        {
            AdvanceadjustmentPreparedByUsers = new HashSet<Advanceadjustment>();
            AdvanceadjustmentUpdatedByUsers = new HashSet<Advanceadjustment>();
            AdvanceadjustmentdetailPreparedByUsers = new HashSet<Advanceadjustmentdetail>();
            AdvanceadjustmentdetailUpdatedByUsers = new HashSet<Advanceadjustmentdetail>();
            Aspnetuserclaims = new HashSet<Aspnetuserclaim>();
            Aspnetuserlogins = new HashSet<Aspnetuserlogin>();
            Aspnetuserroles = new HashSet<Aspnetuserrole>();
            Aspnetusertokens = new HashSet<Aspnetusertoken>();
            ChargetypePreparedByUsers = new HashSet<Chargetype>();
            ChargetypeUpdatedByUsers = new HashSet<Chargetype>();
            CityPreparedByUsers = new HashSet<City>();
            CityUpdatedByUsers = new HashSet<City>();
            CompanyPreparedByUsers = new HashSet<Company>();
            CompanyUpdatedByUsers = new HashSet<Company>();
            ContravoucherPreparedByUsers = new HashSet<Contravoucher>();
            ContravoucherUpdatedByUsers = new HashSet<Contravoucher>();
            ContravoucherdetailPreparedByUsers = new HashSet<Contravoucherdetail>();
            ContravoucherdetailUpdatedByUsers = new HashSet<Contravoucherdetail>();
            CountryPreparedByUsers = new HashSet<Country>();
            CountryUpdatedByUsers = new HashSet<Country>();
            CreditnotePreparedByUsers = new HashSet<Creditnote>();
            CreditnoteUpdatedByUsers = new HashSet<Creditnote>();
            CreditnotedetailtaxPreparedByUsers = new HashSet<Creditnotedetailtax>();
            CreditnotedetailtaxUpdatedByUsers = new HashSet<Creditnotedetailtax>();
            CreditnotetaxPreparedByUsers = new HashSet<Creditnotetax>();
            CreditnotetaxUpdatedByUsers = new HashSet<Creditnotetax>();
            CurrencyPreparedByUsers = new HashSet<Currency>();
            CurrencyUpdatedByUsers = new HashSet<Currency>();
            CurrencyconversionPreparedByUsers = new HashSet<Currencyconversion>();
            CurrencyconversionUpdatedByUsers = new HashSet<Currencyconversion>();
            DebitnotePreparedByUsers = new HashSet<Debitnote>();
            DebitnoteUpdatedByUsers = new HashSet<Debitnote>();
            DebitnotedetailPreparedByUsers = new HashSet<Debitnotedetail>();
            DebitnotedetailUpdatedByUsers = new HashSet<Debitnotedetail>();
            DebitnotedetailtaxPreparedByUsers = new HashSet<Debitnotedetailtax>();
            DebitnotedetailtaxUpdatedByUsers = new HashSet<Debitnotedetailtax>();
            DebitnotetaxPreparedByUsers = new HashSet<Debitnotetax>();
            DebitnotetaxUpdatedByUsers = new HashSet<Debitnotetax>();
            DepartmentPreparedByUsers = new HashSet<Department>();
            DepartmentUpdatedByUsers = new HashSet<Department>();
            DesignationPreparedByUsers = new HashSet<Designation>();
            DesignationUpdatedByUsers = new HashSet<Designation>();
            EmployeePreparedByUsers = new HashSet<Employee>();
            EmployeeUpdatedByUsers = new HashSet<Employee>();
            FinancialyearPreparedByUsers = new HashSet<Financialyear>();
            FinancialyearUpdatedByUsers = new HashSet<Financialyear>();
            FinancialyearcompanyrelationPreparedByUsers = new HashSet<Financialyearcompanyrelation>();
            FinancialyearcompanyrelationUpdatedByUsers = new HashSet<Financialyearcompanyrelation>();
            FormPreparedByUsers = new HashSet<Form>();
            FormUpdatedByUsers = new HashSet<Form>();
            JournalvoucherPreparedByUsers = new HashSet<Journalvoucher>();
            JournalvoucherUpdatedByUsers = new HashSet<Journalvoucher>();
            JournalvoucherdetailPreparedByUsers = new HashSet<Journalvoucherdetail>();
            JournalvoucherdetailUpdatedByUsers = new HashSet<Journalvoucherdetail>();
            LedgerPreparedByUsers = new HashSet<Ledger>();
            LedgerUpdatedByUsers = new HashSet<Ledger>();
            LedgeraddressPreparedByUsers = new HashSet<Ledgeraddress>();
            LedgeraddressUpdatedByUsers = new HashSet<Ledgeraddress>();
            LedgercompanyrelationPreparedByUsers = new HashSet<Ledgercompanyrelation>();
            LedgercompanyrelationUpdatedByUsers = new HashSet<Ledgercompanyrelation>();
            LedgerfinancialyearbalancePreparedByUsers = new HashSet<Ledgerfinancialyearbalance>();
            LedgerfinancialyearbalanceUpdatedByUsers = new HashSet<Ledgerfinancialyearbalance>();
            ModulePreparedByUsers = new HashSet<Module>();
            ModuleUpdatedByUsers = new HashSet<Module>();
            PaymentvoucherPreparedByUsers = new HashSet<Paymentvoucher>();
            PaymentvoucherUpdatedByUsers = new HashSet<Paymentvoucher>();
            PaymentvoucherdetailPreparedByUsers = new HashSet<Paymentvoucherdetail>();
            PaymentvoucherdetailUpdatedByUsers = new HashSet<Paymentvoucherdetail>();
            PurchaseinvoicePreparedByUsers = new HashSet<Purchaseinvoice>();
            PurchaseinvoiceUpdatedByUsers = new HashSet<Purchaseinvoice>();
            PurchaseinvoicedetailPreparedByUsers = new HashSet<Purchaseinvoicedetail>();
            PurchaseinvoicedetailUpdatedByUsers = new HashSet<Purchaseinvoicedetail>();
            PurchaseinvoicedetailtaxPreparedByUsers = new HashSet<Purchaseinvoicedetailtax>();
            PurchaseinvoicedetailtaxUpdatedByUsers = new HashSet<Purchaseinvoicedetailtax>();
            PurchaseinvoicetaxPreparedByUsers = new HashSet<Purchaseinvoicetax>();
            PurchaseinvoicetaxUpdatedByUsers = new HashSet<Purchaseinvoicetax>();
            ReceiptvoucherPreparedByUsers = new HashSet<Receiptvoucher>();
            ReceiptvoucherUpdatedByUsers = new HashSet<Receiptvoucher>();
            ReceiptvoucherdetailPreparedByUsers = new HashSet<Receiptvoucherdetail>();
            ReceiptvoucherdetailUpdatedByUsers = new HashSet<Receiptvoucherdetail>();
            SalesinvoicePreparedByUsers = new HashSet<Salesinvoice>();
            SalesinvoiceUpdatedByUsers = new HashSet<Salesinvoice>();
            SalesinvoicedetailPreparedByUsers = new HashSet<Salesinvoicedetail>();
            SalesinvoicedetailUpdatedByUsers = new HashSet<Salesinvoicedetail>();
            SalesinvoicedetailtaxPreparedByUsers = new HashSet<Salesinvoicedetailtax>();
            SalesinvoicedetailtaxUpdatedByUsers = new HashSet<Salesinvoicedetailtax>();
            SalesinvoicetaxPreparedByUsers = new HashSet<Salesinvoicetax>();
            SalesinvoicetaxUpdatedByUsers = new HashSet<Salesinvoicetax>();
            StatePreparedByUsers = new HashSet<State>();
            StateUpdatedByUsers = new HashSet<State>();
            StatusPreparedByUsers = new HashSet<Status>();
            StatusUpdatedByUsers = new HashSet<Status>();
            TaxregisterPreparedByUsers = new HashSet<Taxregister>();
            TaxregisterUpdatedByUsers = new HashSet<Taxregister>();
            TaxregisterdetailPreparedByUsers = new HashSet<Taxregisterdetail>();
            TaxregisterdetailUpdatedByUsers = new HashSet<Taxregisterdetail>();
            UnitofmeasurementPreparedByUsers = new HashSet<Unitofmeasurement>();
            UnitofmeasurementUpdatedByUsers = new HashSet<Unitofmeasurement>();
            VouchersetupPreparedByUsers = new HashSet<Vouchersetup>();
            VouchersetupUpdatedByUsers = new HashSet<Vouchersetup>();
            VouchersetupdetailPreparedByUsers = new HashSet<Vouchersetupdetail>();
            VouchersetupdetailUpdatedByUsers = new HashSet<Vouchersetupdetail>();
            VoucherstylePreparedByUsers = new HashSet<Voucherstyle>();
            VoucherstyleUpdatedByUsers = new HashSet<Voucherstyle>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public DateTime? LockoutEnd { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public int EmployeeId { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual ICollection<Advanceadjustment> AdvanceadjustmentPreparedByUsers { get; set; }
        public virtual ICollection<Advanceadjustment> AdvanceadjustmentUpdatedByUsers { get; set; }
        public virtual ICollection<Advanceadjustmentdetail> AdvanceadjustmentdetailPreparedByUsers { get; set; }
        public virtual ICollection<Advanceadjustmentdetail> AdvanceadjustmentdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Aspnetuserclaim> Aspnetuserclaims { get; set; }
        public virtual ICollection<Aspnetuserlogin> Aspnetuserlogins { get; set; }
        public virtual ICollection<Aspnetuserrole> Aspnetuserroles { get; set; }
        public virtual ICollection<Aspnetusertoken> Aspnetusertokens { get; set; }
        public virtual ICollection<Chargetype> ChargetypePreparedByUsers { get; set; }
        public virtual ICollection<Chargetype> ChargetypeUpdatedByUsers { get; set; }
        public virtual ICollection<City> CityPreparedByUsers { get; set; }
        public virtual ICollection<City> CityUpdatedByUsers { get; set; }
        public virtual ICollection<Company> CompanyPreparedByUsers { get; set; }
        public virtual ICollection<Company> CompanyUpdatedByUsers { get; set; }
        public virtual ICollection<Contravoucher> ContravoucherPreparedByUsers { get; set; }
        public virtual ICollection<Contravoucher> ContravoucherUpdatedByUsers { get; set; }
        public virtual ICollection<Contravoucherdetail> ContravoucherdetailPreparedByUsers { get; set; }
        public virtual ICollection<Contravoucherdetail> ContravoucherdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Country> CountryPreparedByUsers { get; set; }
        public virtual ICollection<Country> CountryUpdatedByUsers { get; set; }
        public virtual ICollection<Creditnote> CreditnotePreparedByUsers { get; set; }
        public virtual ICollection<Creditnote> CreditnoteUpdatedByUsers { get; set; }
        public virtual ICollection<Creditnotedetailtax> CreditnotedetailtaxPreparedByUsers { get; set; }
        public virtual ICollection<Creditnotedetailtax> CreditnotedetailtaxUpdatedByUsers { get; set; }
        public virtual ICollection<Creditnotetax> CreditnotetaxPreparedByUsers { get; set; }
        public virtual ICollection<Creditnotetax> CreditnotetaxUpdatedByUsers { get; set; }
        public virtual ICollection<Currency> CurrencyPreparedByUsers { get; set; }
        public virtual ICollection<Currency> CurrencyUpdatedByUsers { get; set; }
        public virtual ICollection<Currencyconversion> CurrencyconversionPreparedByUsers { get; set; }
        public virtual ICollection<Currencyconversion> CurrencyconversionUpdatedByUsers { get; set; }
        public virtual ICollection<Debitnote> DebitnotePreparedByUsers { get; set; }
        public virtual ICollection<Debitnote> DebitnoteUpdatedByUsers { get; set; }
        public virtual ICollection<Debitnotedetail> DebitnotedetailPreparedByUsers { get; set; }
        public virtual ICollection<Debitnotedetail> DebitnotedetailUpdatedByUsers { get; set; }
        public virtual ICollection<Debitnotedetailtax> DebitnotedetailtaxPreparedByUsers { get; set; }
        public virtual ICollection<Debitnotedetailtax> DebitnotedetailtaxUpdatedByUsers { get; set; }
        public virtual ICollection<Debitnotetax> DebitnotetaxPreparedByUsers { get; set; }
        public virtual ICollection<Debitnotetax> DebitnotetaxUpdatedByUsers { get; set; }
        public virtual ICollection<Department> DepartmentPreparedByUsers { get; set; }
        public virtual ICollection<Department> DepartmentUpdatedByUsers { get; set; }
        public virtual ICollection<Designation> DesignationPreparedByUsers { get; set; }
        public virtual ICollection<Designation> DesignationUpdatedByUsers { get; set; }
        public virtual ICollection<Employee> EmployeePreparedByUsers { get; set; }
        public virtual ICollection<Employee> EmployeeUpdatedByUsers { get; set; }
        public virtual ICollection<Financialyear> FinancialyearPreparedByUsers { get; set; }
        public virtual ICollection<Financialyear> FinancialyearUpdatedByUsers { get; set; }
        public virtual ICollection<Financialyearcompanyrelation> FinancialyearcompanyrelationPreparedByUsers { get; set; }
        public virtual ICollection<Financialyearcompanyrelation> FinancialyearcompanyrelationUpdatedByUsers { get; set; }
        public virtual ICollection<Form> FormPreparedByUsers { get; set; }
        public virtual ICollection<Form> FormUpdatedByUsers { get; set; }
        public virtual ICollection<Journalvoucher> JournalvoucherPreparedByUsers { get; set; }
        public virtual ICollection<Journalvoucher> JournalvoucherUpdatedByUsers { get; set; }
        public virtual ICollection<Journalvoucherdetail> JournalvoucherdetailPreparedByUsers { get; set; }
        public virtual ICollection<Journalvoucherdetail> JournalvoucherdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Ledger> LedgerPreparedByUsers { get; set; }
        public virtual ICollection<Ledger> LedgerUpdatedByUsers { get; set; }
        public virtual ICollection<Ledgeraddress> LedgeraddressPreparedByUsers { get; set; }
        public virtual ICollection<Ledgeraddress> LedgeraddressUpdatedByUsers { get; set; }
        public virtual ICollection<Ledgercompanyrelation> LedgercompanyrelationPreparedByUsers { get; set; }
        public virtual ICollection<Ledgercompanyrelation> LedgercompanyrelationUpdatedByUsers { get; set; }
        public virtual ICollection<Ledgerfinancialyearbalance> LedgerfinancialyearbalancePreparedByUsers { get; set; }
        public virtual ICollection<Ledgerfinancialyearbalance> LedgerfinancialyearbalanceUpdatedByUsers { get; set; }
        public virtual ICollection<Module> ModulePreparedByUsers { get; set; }
        public virtual ICollection<Module> ModuleUpdatedByUsers { get; set; }
        public virtual ICollection<Paymentvoucher> PaymentvoucherPreparedByUsers { get; set; }
        public virtual ICollection<Paymentvoucher> PaymentvoucherUpdatedByUsers { get; set; }
        public virtual ICollection<Paymentvoucherdetail> PaymentvoucherdetailPreparedByUsers { get; set; }
        public virtual ICollection<Paymentvoucherdetail> PaymentvoucherdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoice> PurchaseinvoicePreparedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoice> PurchaseinvoiceUpdatedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicedetail> PurchaseinvoicedetailPreparedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicedetail> PurchaseinvoicedetailUpdatedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicedetailtax> PurchaseinvoicedetailtaxPreparedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicedetailtax> PurchaseinvoicedetailtaxUpdatedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicetax> PurchaseinvoicetaxPreparedByUsers { get; set; }
        public virtual ICollection<Purchaseinvoicetax> PurchaseinvoicetaxUpdatedByUsers { get; set; }
        public virtual ICollection<Receiptvoucher> ReceiptvoucherPreparedByUsers { get; set; }
        public virtual ICollection<Receiptvoucher> ReceiptvoucherUpdatedByUsers { get; set; }
        public virtual ICollection<Receiptvoucherdetail> ReceiptvoucherdetailPreparedByUsers { get; set; }
        public virtual ICollection<Receiptvoucherdetail> ReceiptvoucherdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Salesinvoice> SalesinvoicePreparedByUsers { get; set; }
        public virtual ICollection<Salesinvoice> SalesinvoiceUpdatedByUsers { get; set; }
        public virtual ICollection<Salesinvoicedetail> SalesinvoicedetailPreparedByUsers { get; set; }
        public virtual ICollection<Salesinvoicedetail> SalesinvoicedetailUpdatedByUsers { get; set; }
        public virtual ICollection<Salesinvoicedetailtax> SalesinvoicedetailtaxPreparedByUsers { get; set; }
        public virtual ICollection<Salesinvoicedetailtax> SalesinvoicedetailtaxUpdatedByUsers { get; set; }
        public virtual ICollection<Salesinvoicetax> SalesinvoicetaxPreparedByUsers { get; set; }
        public virtual ICollection<Salesinvoicetax> SalesinvoicetaxUpdatedByUsers { get; set; }
        public virtual ICollection<State> StatePreparedByUsers { get; set; }
        public virtual ICollection<State> StateUpdatedByUsers { get; set; }
        public virtual ICollection<Status> StatusPreparedByUsers { get; set; }
        public virtual ICollection<Status> StatusUpdatedByUsers { get; set; }
        public virtual ICollection<Taxregister> TaxregisterPreparedByUsers { get; set; }
        public virtual ICollection<Taxregister> TaxregisterUpdatedByUsers { get; set; }
        public virtual ICollection<Taxregisterdetail> TaxregisterdetailPreparedByUsers { get; set; }
        public virtual ICollection<Taxregisterdetail> TaxregisterdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Unitofmeasurement> UnitofmeasurementPreparedByUsers { get; set; }
        public virtual ICollection<Unitofmeasurement> UnitofmeasurementUpdatedByUsers { get; set; }
        public virtual ICollection<Vouchersetup> VouchersetupPreparedByUsers { get; set; }
        public virtual ICollection<Vouchersetup> VouchersetupUpdatedByUsers { get; set; }
        public virtual ICollection<Vouchersetupdetail> VouchersetupdetailPreparedByUsers { get; set; }
        public virtual ICollection<Vouchersetupdetail> VouchersetupdetailUpdatedByUsers { get; set; }
        public virtual ICollection<Voucherstyle> VoucherstylePreparedByUsers { get; set; }
        public virtual ICollection<Voucherstyle> VoucherstyleUpdatedByUsers { get; set; }
    }
}