// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Attachment
    {
        public Attachment()
        {
            Advanceadjustmentattachments = new HashSet<Advanceadjustmentattachment>();
            Contravoucherattachments = new HashSet<Contravoucherattachment>();
            Creditnoteattachments = new HashSet<Creditnoteattachment>();
            Debitnoteattachments = new HashSet<Debitnoteattachment>();
            Journalvoucherattachments = new HashSet<Journalvoucherattachment>();
            Ledgerattachments = new HashSet<Ledgerattachment>();
            Paymentvoucherattachments = new HashSet<Paymentvoucherattachment>();
            Purchaseinvoiceattachments = new HashSet<Purchaseinvoiceattachment>();
            Receiptvoucherattachments = new HashSet<Receiptvoucherattachment>();
            Salesinvoiceattachments = new HashSet<Salesinvoiceattachment>();
        }

        public int AttachmentId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string ContainerName { get; set; }
        public string ServerFileName { get; set; }
        public string UserFileName { get; set; }
        public string FileExtension { get; set; }
        public string ContentType { get; set; }
        public long? ContentLength { get; set; }
        public int StorageAccountId { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Attachmentcategory Category { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Attachmentstorageaccount StorageAccount { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Advanceadjustmentattachment> Advanceadjustmentattachments { get; set; }
        public virtual ICollection<Contravoucherattachment> Contravoucherattachments { get; set; }
        public virtual ICollection<Creditnoteattachment> Creditnoteattachments { get; set; }
        public virtual ICollection<Debitnoteattachment> Debitnoteattachments { get; set; }
        public virtual ICollection<Journalvoucherattachment> Journalvoucherattachments { get; set; }
        public virtual ICollection<Ledgerattachment> Ledgerattachments { get; set; }
        public virtual ICollection<Paymentvoucherattachment> Paymentvoucherattachments { get; set; }
        public virtual ICollection<Purchaseinvoiceattachment> Purchaseinvoiceattachments { get; set; }
        public virtual ICollection<Receiptvoucherattachment> Receiptvoucherattachments { get; set; }
        public virtual ICollection<Salesinvoiceattachment> Salesinvoiceattachments { get; set; }
    }
}