// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Attachmentstorageaccount
    {
        public Attachmentstorageaccount()
        {
            Attachments = new HashSet<Attachment>();
        }

        public int StorageAccountId { get; set; }
        public string AccountName { get; set; }
        public string AccountKey { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
    }
}