// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class City
    {
        public City()
        {
            Ledgeraddresses = new HashSet<Ledgeraddress>();
        }

        public int CityId { get; set; }
        public string CityName { get; set; }
        public int StateId { get; set; }
        public int? PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual State State { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Ledgeraddress> Ledgeraddresses { get; set; }
    }
}