// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Contravoucherdetail
    {
        public int ContraVoucherDetId { get; set; }
        public int ContraVoucherId { get; set; }
        public int ParticularLedgerId { get; set; }
        public string Narration { get; set; }
        public decimal DebitAmountFc { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmountFc { get; set; }
        public decimal CreditAmount { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Contravoucher ContraVoucher { get; set; }
        public virtual Ledger ParticularLedger { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}