// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("contravoucherdetail")]
    public partial class Contravoucherdetail
    {
        [Key]
        public int ContraVoucherDetId { get; set; }
        public int? ContraVoucherId { get; set; }
        public int? ParticularLedgerId { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        [Column("DebitAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? DebitAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? DebitAmount { get; set; }
        [Column("CreditAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? CreditAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? CreditAmount { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(ContraVoucherId))]
        [InverseProperty(nameof(Contravoucher.Contravoucherdetails))]
        public virtual Contravoucher ContraVoucher { get; set; }
        [ForeignKey(nameof(ParticularLedgerId))]
        [InverseProperty(nameof(Ledger.Contravoucherdetails))]
        public virtual Ledger ParticularLedger { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ContravoucherdetailPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ContravoucherdetailUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}