// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("country")]
    public partial class Country
    {
        public Country()
        {
            Ledgeraddresses = new HashSet<Ledgeraddress>();
            States = new HashSet<State>();
        }

        [Key]
        public int CountryId { get; set; }
        [Required]
        [Column(TypeName = "varchar(500)")]
        public string CountryName { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.CountryPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.CountryUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [InverseProperty(nameof(Ledgeraddress.Country))]
        public virtual ICollection<Ledgeraddress> Ledgeraddresses { get; set; }
        [InverseProperty(nameof(State.Country))]
        public virtual ICollection<State> States { get; set; }
    }
}