// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Currencyconversion
    {
        public int ConversionId { get; set; }
        public int? CompanyId { get; set; }
        public int? CurrencyId { get; set; }
        public DateTime? EffectiveDateTime { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Company Company { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}