// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("debitnotedetailtax")]
    public partial class Debitnotedetailtax
    {
        [Key]
        public int DebitNoteDetTaxId { get; set; }
        public int? DebitNoteDetId { get; set; }
        public int? SrNo { get; set; }
        public int? TaxLedgerId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string TaxPercentageOrAmount { get; set; }
        [Column("TaxPerOrAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? TaxPerOrAmountFc { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string TaxAddOrDeduct { get; set; }
        [Column("TaxAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? TaxAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? TaxAmount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Remark { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(DebitNoteDetId))]
        [InverseProperty(nameof(Debitnotedetail.Debitnotedetailtaxes))]
        public virtual Debitnotedetail DebitNoteDet { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.DebitnotedetailtaxPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(TaxLedgerId))]
        [InverseProperty(nameof(Ledger.Debitnotedetailtaxes))]
        public virtual Ledger TaxLedger { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.DebitnotedetailtaxUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}