// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("employee")]
    public partial class Employee
    {
        [Key]
        public int EmployeeId { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string EmployeeCode { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string FirstName { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string LastName { get; set; }
        public int? DesignationId { get; set; }
        public int? DepartmentId { get; set; }
        [Column(TypeName = "text")]
        public string EmailAddress { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(DepartmentId))]
        [InverseProperty("Employees")]
        public virtual Department Department { get; set; }
        [ForeignKey(nameof(DesignationId))]
        [InverseProperty("Employees")]
        public virtual Designation Designation { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.EmployeePreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.EmployeeUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}