// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("financialyear")]
    public partial class Financialyear
    {
        public Financialyear()
        {
            Financialyearcompanyrelations = new HashSet<Financialyearcompanyrelation>();
            Ledgerfinancialyearbalances = new HashSet<Ledgerfinancialyearbalance>();
            Purchaseinvoices = new HashSet<Purchaseinvoice>();
            Salesinvoices = new HashSet<Salesinvoice>();
            Vouchersetupdetails = new HashSet<Vouchersetupdetail>();
        }

        [Key]
        public int FinancialYearId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string FinancialYearName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FromDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ToDate { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(User.FinancialyearPreparedByUsers))]
        public virtual User PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(User.FinancialyearUpdatedByUsers))]
        public virtual User UpdatedByUser { get; set; }
        [InverseProperty(nameof(Financialyearcompanyrelation.FinancialYear))]
        public virtual ICollection<Financialyearcompanyrelation> Financialyearcompanyrelations { get; set; }
        [InverseProperty(nameof(Ledgerfinancialyearbalance.FinancialYear))]
        public virtual ICollection<Ledgerfinancialyearbalance> Ledgerfinancialyearbalances { get; set; }
        [InverseProperty(nameof(Purchaseinvoice.FinancialYear))]
        public virtual ICollection<Purchaseinvoice> Purchaseinvoices { get; set; }
        [InverseProperty(nameof(Salesinvoice.FinancialYear))]
        public virtual ICollection<Salesinvoice> Salesinvoices { get; set; }
        [InverseProperty(nameof(Vouchersetupdetail.FinancialYear))]
        public virtual ICollection<Vouchersetupdetail> Vouchersetupdetails { get; set; }
    }
}