// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Journalvoucherdetail
    {
        public int JournalVoucherDetId { get; set; }
        public int JournalVoucherId { get; set; }
        public int ParticularLedgerId { get; set; }
        public int TransactionTypeId { get; set; }
        public string Narration { get; set; }
        public int? SalesInvoiceId { get; set; }
        public int? PurchaseInvoiceId { get; set; }
        public int? CreditNoteId { get; set; }
        public int? DebitNoteId { get; set; }
        public decimal DebitAmountFc { get; set; }
        public decimal DebitAmount { get; set; }
        public decimal CreditAmountFc { get; set; }
        public decimal CreditAmount { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Creditnote CreditNote { get; set; }
        public virtual Debitnote DebitNote { get; set; }
        public virtual Journalvoucher JournalVoucher { get; set; }
        public virtual Ledger ParticularLedger { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Purchaseinvoice PurchaseInvoice { get; set; }
        public virtual Salesinvoice SalesInvoice { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}