// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("journalvoucherdetail")]
    public partial class Journalvoucherdetail
    {
        [Key]
        public int JournalVoucherDetId { get; set; }
        public int? JournalVoucherId { get; set; }
        public int? ParticularLedgerId { get; set; }
        public int? TransactionTypeId { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        public int? SalesInvoiceId { get; set; }
        public int? PurchaseInvoiceId { get; set; }
        public int? CreditNoteId { get; set; }
        public int? DebitNoteId { get; set; }
        [Column("DebitAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? DebitAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? DebitAmount { get; set; }
        [Column("CreditAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? CreditAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? CreditAmount { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(CreditNoteId))]
        [InverseProperty(nameof(Creditnote.Journalvoucherdetails))]
        public virtual Creditnote CreditNote { get; set; }
        [ForeignKey(nameof(DebitNoteId))]
        [InverseProperty(nameof(Debitnote.Journalvoucherdetails))]
        public virtual Debitnote DebitNote { get; set; }
        [ForeignKey(nameof(JournalVoucherId))]
        [InverseProperty(nameof(Journalvoucher.Journalvoucherdetails))]
        public virtual Journalvoucher JournalVoucher { get; set; }
        [ForeignKey(nameof(ParticularLedgerId))]
        [InverseProperty(nameof(Ledger.Journalvoucherdetails))]
        public virtual Ledger ParticularLedger { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.JournalvoucherdetailPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(PurchaseInvoiceId))]
        [InverseProperty(nameof(Purchaseinvoice.Journalvoucherdetails))]
        public virtual Purchaseinvoice PurchaseInvoice { get; set; }
        [ForeignKey(nameof(SalesInvoiceId))]
        [InverseProperty(nameof(Salesinvoice.Journalvoucherdetails))]
        public virtual Salesinvoice SalesInvoice { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.JournalvoucherdetailUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}