// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("journalvoucher")]
    public partial class Journalvoucher
    {
        public Journalvoucher()
        {
            Journalvoucherdetails = new HashSet<Journalvoucherdetail>();
        }

        [Key]
        public int JournalVoucherId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string VoucherNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? VoucherDate { get; set; }
        public int CurrencyId { get; set; }
        [Column(TypeName = "decimal(18,6)")]
        public decimal ExchangeRate { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        [Column("Amount_FC", TypeName = "decimal(18,4)")]
        public decimal? AmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? Amount { get; set; }
        [Column("Amount_FCInWord", TypeName = "varchar(2000)")]
        public string AmountFcinWord { get; set; }
        [Column("DebitAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? DebitAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? DebitAmount { get; set; }
        [Column("CreditAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? CreditAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? CreditAmount { get; set; }
        public int? StatusId { get; set; }
        public int? CompanyId { get; set; }
        public int? FinancialYearId { get; set; }
        public int? MaxNo { get; set; }
        public int? VoucherStyleId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(CompanyId))]
        [InverseProperty("Journalvouchers")]
        public virtual Company Company { get; set; }
        [ForeignKey(nameof(CurrencyId))]
        [InverseProperty("Journalvouchers")]
        public virtual Currency Currency { get; set; }
        [ForeignKey(nameof(FinancialYearId))]
        [InverseProperty(nameof(Financialyear.Journalvouchers))]
        public virtual Financialyear FinancialYear { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.JournalvoucherPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty("Journalvouchers")]
        public virtual Status Status { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.JournalvoucherUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [ForeignKey(nameof(VoucherStyleId))]
        [InverseProperty(nameof(Voucherstyle.Journalvouchers))]
        public virtual Voucherstyle VoucherStyle { get; set; }
        [InverseProperty(nameof(Journalvoucherdetail.JournalVoucher))]
        public virtual ICollection<Journalvoucherdetail> Journalvoucherdetails { get; set; }
    }
}