// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Ledgeraddress
    {
        public Ledgeraddress()
        {
            Creditnotes = new HashSet<Creditnote>();
            Debitnotes = new HashSet<Debitnote>();
            Purchaseinvoices = new HashSet<Purchaseinvoice>();
            Salesinvoices = new HashSet<Salesinvoice>();
        }

        public int AddressId { get; set; }
        public int LedgerId { get; set; }
        public string AddressDescription { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public int CityId { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNo { get; set; }
        public string PostalCode { get; set; }
        public string FaxNo { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual State State { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Creditnote> Creditnotes { get; set; }
        public virtual ICollection<Debitnote> Debitnotes { get; set; }
        public virtual ICollection<Purchaseinvoice> Purchaseinvoices { get; set; }
        public virtual ICollection<Salesinvoice> Salesinvoices { get; set; }
    }
}