// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("module")]
    public partial class Module
    {
        public Module()
        {
            Forms = new HashSet<Form>();
            Vouchersetups = new HashSet<Vouchersetup>();
        }

        [Key]
        public int ModuleId { get; set; }
        [Required]
        [Column(TypeName = "varchar(500)")]
        public string ModuleName { get; set; }
        public sbyte? IsActive { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(User.ModulePreparedByUsers))]
        public virtual User PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(User.ModuleUpdatedByUsers))]
        public virtual User UpdatedByUser { get; set; }
        [InverseProperty(nameof(Form.Module))]
        public virtual ICollection<Form> Forms { get; set; }
        [InverseProperty(nameof(Vouchersetup.Module))]
        public virtual ICollection<Vouchersetup> Vouchersetups { get; set; }
    }
}