// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Module
    {
        public Module()
        {
            Forms = new HashSet<Form>();
            Vouchersetups = new HashSet<Vouchersetup>();
        }

        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public sbyte IsActive { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Form> Forms { get; set; }
        public virtual ICollection<Vouchersetup> Vouchersetups { get; set; }
    }
}