// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("paymentvoucherdetail")]
    public partial class Paymentvoucherdetail
    {
        [Key]
        public int PaymentVoucherDetId { get; set; }
        public int? PaymentVoucherId { get; set; }
        public int? ParticularLedgerId { get; set; }
        public int? TransactionTypeId { get; set; }
        [Column("Amount_FC", TypeName = "decimal(18,4)")]
        public decimal? AmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        public int? PurchaseInvoiceId { get; set; }
        public int? CreditNoteId { get; set; }
        public int? DebitNoteId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(CreditNoteId))]
        [InverseProperty(nameof(Creditnote.Paymentvoucherdetails))]
        public virtual Creditnote CreditNote { get; set; }
        [ForeignKey(nameof(DebitNoteId))]
        [InverseProperty(nameof(Debitnote.Paymentvoucherdetails))]
        public virtual Debitnote DebitNote { get; set; }
        [ForeignKey(nameof(ParticularLedgerId))]
        [InverseProperty(nameof(Ledger.Paymentvoucherdetails))]
        public virtual Ledger ParticularLedger { get; set; }
        [ForeignKey(nameof(PaymentVoucherId))]
        [InverseProperty(nameof(Paymentvoucher.Paymentvoucherdetails))]
        public virtual Paymentvoucher PaymentVoucher { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.PaymentvoucherdetailPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(PurchaseInvoiceId))]
        [InverseProperty(nameof(Purchaseinvoice.Paymentvoucherdetails))]
        public virtual Purchaseinvoice PurchaseInvoice { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.PaymentvoucherdetailUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}