// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("purchaseinvoicetax")]
    public partial class Purchaseinvoicetax
    {
        [Key]
        public int PurchaseInvoiceTaxId { get; set; }
        public int? PurchaseInvoiceId { get; set; }
        public int? SrNo { get; set; }
        public int? TaxLedgerId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string TaxPercentageOrAmount { get; set; }
        [Column("TaxPerOrAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? TaxPerOrAmountFc { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string TaxAddOrDeduct { get; set; }
        [Column("TaxAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? TaxAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? TaxAmount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Remark { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(User.PurchaseinvoicetaxPreparedByUsers))]
        public virtual User PreparedByUser { get; set; }
        [ForeignKey(nameof(PurchaseInvoiceId))]
        [InverseProperty(nameof(Purchaseinvoice.Purchaseinvoicetaxes))]
        public virtual Purchaseinvoice PurchaseInvoice { get; set; }
        [ForeignKey(nameof(TaxLedgerId))]
        [InverseProperty(nameof(Ledger.Purchaseinvoicetaxes))]
        public virtual Ledger TaxLedger { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(User.PurchaseinvoicetaxUpdatedByUsers))]
        public virtual User UpdatedByUser { get; set; }
    }
}