// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("purchaseinvoicecharges")]
    public partial class Purchaseinvoicecharge
    {
        [Key]
        public int InvoiceChargesId { get; set; }
        public int? InvoiceId { get; set; }
        public int? SrNo { get; set; }
        public int? ChargeTypeId { get; set; }
        [Column("ChargeAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? ChargeAmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? ChargeAmount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Remark { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(ChargeTypeId))]
        [InverseProperty(nameof(Chargetype.Purchaseinvoicecharges))]
        public virtual Chargetype ChargeType { get; set; }
        [ForeignKey(nameof(InvoiceId))]
        [InverseProperty(nameof(Purchaseinvoice.Purchaseinvoicecharges))]
        public virtual Purchaseinvoice Invoice { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(User.PurchaseinvoicechargePreparedByUsers))]
        public virtual User PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(User.PurchaseinvoicechargeUpdatedByUsers))]
        public virtual User UpdatedByUser { get; set; }
    }
}