// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    /// <summary>
    /// FK_ReceiptVoucherDetails_Ledger_ParticularLedgerId
    /// </summary>
    [Table("receiptvoucherdetail")]
    public partial class Receiptvoucherdetail
    {
        [Key]
        public int ReceiptVoucherDetId { get; set; }
        public int? ReceiptVoucherId { get; set; }
        public int? ParticularLedgerId { get; set; }
        public int? TransactionTypeId { get; set; }
        [Column("Amount_FC", TypeName = "decimal(18,4)")]
        public decimal? AmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? Amount { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        public int? SalesInvoiceId { get; set; }
        public int? CreditNoteId { get; set; }
        public int? DebitNoteId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(CreditNoteId))]
        [InverseProperty(nameof(Creditnote.Receiptvoucherdetails))]
        public virtual Creditnote CreditNote { get; set; }
        [ForeignKey(nameof(DebitNoteId))]
        [InverseProperty(nameof(Debitnote.Receiptvoucherdetails))]
        public virtual Debitnote DebitNote { get; set; }
        [ForeignKey(nameof(ParticularLedgerId))]
        [InverseProperty(nameof(Ledger.Receiptvoucherdetails))]
        public virtual Ledger ParticularLedger { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ReceiptvoucherdetailPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(ReceiptVoucherId))]
        [InverseProperty(nameof(Receiptvoucher.Receiptvoucherdetails))]
        public virtual Receiptvoucher ReceiptVoucher { get; set; }
        [ForeignKey(nameof(SalesInvoiceId))]
        [InverseProperty(nameof(Salesinvoice.Receiptvoucherdetails))]
        public virtual Salesinvoice SalesInvoice { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ReceiptvoucherdetailUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}