// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("receiptvoucher")]
    public partial class Receiptvoucher
    {
        public Receiptvoucher()
        {
            Advanceadjustments = new HashSet<Advanceadjustment>();
            Receiptvoucherdetails = new HashSet<Receiptvoucherdetail>();
        }

        [Key]
        public int ReceiptVoucherId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string VoucherNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? VoucherDate { get; set; }
        public int? AccountLedgerId { get; set; }
        [Column(TypeName = "varchar(1)")]
        public string TypeCorB { get; set; }
        public int? ReceiptTypeId { get; set; }
        public int CurrencyId { get; set; }
        [Column(TypeName = "decimal(18,6)")]
        public decimal ExchangeRate { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string ChequeNo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChequeDate { get; set; }
        [Column("ChequeAmount_FC", TypeName = "decimal(18,4)")]
        public decimal? ChequeAmountFc { get; set; }
        [Column(TypeName = "varchar(2000)")]
        public string Narration { get; set; }
        [Column("Amount_FC", TypeName = "decimal(18,4)")]
        public decimal? AmountFc { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal? Amount { get; set; }
        [Column("Amount_FCInWord", TypeName = "varchar(2000)")]
        public string AmountFcinWord { get; set; }
        public int? StatusId { get; set; }
        public int? CompanyId { get; set; }
        public int? FinancialYearId { get; set; }
        public int? MaxNo { get; set; }
        public int? VoucherStyleId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(AccountLedgerId))]
        [InverseProperty(nameof(Ledger.Receiptvouchers))]
        public virtual Ledger AccountLedger { get; set; }
        [ForeignKey(nameof(CompanyId))]
        [InverseProperty("Receiptvouchers")]
        public virtual Company Company { get; set; }
        [ForeignKey(nameof(CurrencyId))]
        [InverseProperty("Receiptvouchers")]
        public virtual Currency Currency { get; set; }
        [ForeignKey(nameof(FinancialYearId))]
        [InverseProperty(nameof(Financialyear.Receiptvouchers))]
        public virtual Financialyear FinancialYear { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ReceiptvoucherPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty("Receiptvouchers")]
        public virtual Status Status { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.ReceiptvoucherUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [ForeignKey(nameof(VoucherStyleId))]
        [InverseProperty(nameof(Voucherstyle.Receiptvouchers))]
        public virtual Voucherstyle VoucherStyle { get; set; }
        [InverseProperty(nameof(Advanceadjustment.ReceiptVoucher))]
        public virtual ICollection<Advanceadjustment> Advanceadjustments { get; set; }
        [InverseProperty(nameof(Receiptvoucherdetail.ReceiptVoucher))]
        public virtual ICollection<Receiptvoucherdetail> Receiptvoucherdetails { get; set; }
    }
}