// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Salesinvoicetax
    {
        public int SalesInvoiceTaxId { get; set; }
        public int SalesInvoiceId { get; set; }
        public int SrNo { get; set; }
        public int TaxLedgerId { get; set; }
        public string TaxPercentageOrAmount { get; set; }
        public decimal TaxPerOrAmountFc { get; set; }
        public string TaxAddOrDeduct { get; set; }
        public decimal TaxAmountFc { get; set; }
        public decimal TaxAmount { get; set; }
        public string Remark { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Salesinvoice SalesInvoice { get; set; }
        public virtual Ledger TaxLedger { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
    }
}