// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("status")]
    public partial class Status
    {
        public Status()
        {
            Advanceadjustments = new HashSet<Advanceadjustment>();
            Contravouchers = new HashSet<Contravoucher>();
            Creditnotes = new HashSet<Creditnote>();
            Debitnotes = new HashSet<Debitnote>();
            Journalvouchers = new HashSet<Journalvoucher>();
            Paymentvouchers = new HashSet<Paymentvoucher>();
            Purchaseinvoices = new HashSet<Purchaseinvoice>();
            Receiptvouchers = new HashSet<Receiptvoucher>();
            Salesinvoices = new HashSet<Salesinvoice>();
        }

        [Key]
        public int StatusId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string StatusName { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.StatusPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.StatusUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [InverseProperty(nameof(Advanceadjustment.Status))]
        public virtual ICollection<Advanceadjustment> Advanceadjustments { get; set; }
        [InverseProperty(nameof(Contravoucher.Status))]
        public virtual ICollection<Contravoucher> Contravouchers { get; set; }
        [InverseProperty(nameof(Creditnote.Status))]
        public virtual ICollection<Creditnote> Creditnotes { get; set; }
        [InverseProperty(nameof(Debitnote.Status))]
        public virtual ICollection<Debitnote> Debitnotes { get; set; }
        [InverseProperty(nameof(Journalvoucher.Status))]
        public virtual ICollection<Journalvoucher> Journalvouchers { get; set; }
        [InverseProperty(nameof(Paymentvoucher.Status))]
        public virtual ICollection<Paymentvoucher> Paymentvouchers { get; set; }
        [InverseProperty(nameof(Purchaseinvoice.Status))]
        public virtual ICollection<Purchaseinvoice> Purchaseinvoices { get; set; }
        [InverseProperty(nameof(Receiptvoucher.Status))]
        public virtual ICollection<Receiptvoucher> Receiptvouchers { get; set; }
        [InverseProperty(nameof(Salesinvoice.Status))]
        public virtual ICollection<Salesinvoice> Salesinvoices { get; set; }
    }
}