// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("state")]
    public partial class State
    {
        public State()
        {
            Cities = new HashSet<City>();
            Ledgeraddresses = new HashSet<Ledgeraddress>();
        }

        [Key]
        public int StateId { get; set; }
        [Column(TypeName = "varchar(500)")]
        public string StateName { get; set; }
        public int? CountryId { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("States")]
        public virtual Country Country { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.StatePreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.StateUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [InverseProperty(nameof(City.State))]
        public virtual ICollection<City> Cities { get; set; }
        [InverseProperty(nameof(Ledgeraddress.State))]
        public virtual ICollection<Ledgeraddress> Ledgeraddresses { get; set; }
    }
}