// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Taxregister
    {
        public Taxregister()
        {
            Creditnotes = new HashSet<Creditnote>();
            Debitnotes = new HashSet<Debitnote>();
            Purchaseinvoices = new HashSet<Purchaseinvoice>();
            Salesinvoices = new HashSet<Salesinvoice>();
            Taxregisterdetails = new HashSet<Taxregisterdetail>();
        }

        public int TaxRegisterId { get; set; }
        public string TaxRegisterName { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Creditnote> Creditnotes { get; set; }
        public virtual ICollection<Debitnote> Debitnotes { get; set; }
        public virtual ICollection<Purchaseinvoice> Purchaseinvoices { get; set; }
        public virtual ICollection<Salesinvoice> Salesinvoices { get; set; }
        public virtual ICollection<Taxregisterdetail> Taxregisterdetails { get; set; }
    }
}