// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Unitofmeasurement
    {
        public Unitofmeasurement()
        {
            Creditnotedetails = new HashSet<Creditnotedetail>();
            Debitnotedetails = new HashSet<Debitnotedetail>();
            Purchaseinvoicedetails = new HashSet<Purchaseinvoicedetail>();
            Salesinvoicedetails = new HashSet<Salesinvoicedetail>();
        }

        public int UnitOfMeasurementId { get; set; }
        public string UnitOfMeasurementName { get; set; }
        public int PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual ICollection<Creditnotedetail> Creditnotedetails { get; set; }
        public virtual ICollection<Debitnotedetail> Debitnotedetails { get; set; }
        public virtual ICollection<Purchaseinvoicedetail> Purchaseinvoicedetails { get; set; }
        public virtual ICollection<Salesinvoicedetail> Salesinvoicedetails { get; set; }
    }
}