// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("unitofmeasurement")]
    public partial class Unitofmeasurement
    {
        public Unitofmeasurement()
        {
            Purchaseinvoicedetails = new HashSet<Purchaseinvoicedetail>();
            Salesinvoicedetails = new HashSet<Salesinvoicedetail>();
        }

        [Key]
        public int UnitOfMeasurementId { get; set; }
        [Column(TypeName = "varchar(250)")]
        public string UnitOfMeasurementName { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(User.UnitofmeasurementPreparedByUsers))]
        public virtual User PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(User.UnitofmeasurementUpdatedByUsers))]
        public virtual User UpdatedByUser { get; set; }
        [InverseProperty(nameof(Purchaseinvoicedetail.UnitOfMeasurement))]
        public virtual ICollection<Purchaseinvoicedetail> Purchaseinvoicedetails { get; set; }
        [InverseProperty(nameof(Salesinvoicedetail.UnitOfMeasurement))]
        public virtual ICollection<Salesinvoicedetail> Salesinvoicedetails { get; set; }
    }
}