// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ERP.DataAccess.EntityModels
{
    public partial class Vouchersetupdetail
    {
        public int VoucherSetupDetId { get; set; }
        public int? VoucherSetupId { get; set; }
        public string NoPad { get; set; }
        public string NoPreString { get; set; }
        public string NoPostString { get; set; }
        public string NoSeparator { get; set; }
        public string FormatText { get; set; }
        public int? VoucherStyleId { get; set; }
        public int? CompanyId { get; set; }
        public int? FinancialYearId { get; set; }
        public int? PreparedByUserId { get; set; }
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        public DateTime? UpdatedDateTime { get; set; }

        public virtual Company Company { get; set; }
        public virtual Financialyear FinancialYear { get; set; }
        public virtual Aspnetuser PreparedByUser { get; set; }
        public virtual Aspnetuser UpdatedByUser { get; set; }
        public virtual Vouchersetup VoucherSetup { get; set; }
        public virtual Voucherstyle VoucherStyle { get; set; }
    }
}