// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.DataAccess.EntityModels
{
    [Table("vouchersetup")]
    public partial class Vouchersetup
    {
        public Vouchersetup()
        {
            Vouchersetupdetails = new HashSet<Vouchersetupdetail>();
        }

        [Key]
        public int VoucherSetupId { get; set; }
        [Required]
        [Column(TypeName = "varchar(500)")]
        public string VoucherSetupName { get; set; }
        public int? ModuleId { get; set; }
        public sbyte? IsActive { get; set; }
        public int? PreparedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PreparedDateTime { get; set; }
        public int? UpdatedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDateTime { get; set; }

        [ForeignKey(nameof(ModuleId))]
        [InverseProperty("Vouchersetups")]
        public virtual Module Module { get; set; }
        [ForeignKey(nameof(PreparedByUserId))]
        [InverseProperty(nameof(Aspnetuser.VouchersetupPreparedByUsers))]
        public virtual Aspnetuser PreparedByUser { get; set; }
        [ForeignKey(nameof(UpdatedByUserId))]
        [InverseProperty(nameof(Aspnetuser.VouchersetupUpdatedByUsers))]
        public virtual Aspnetuser UpdatedByUser { get; set; }
        [InverseProperty(nameof(Vouchersetupdetail.VoucherSetup))]
        public virtual ICollection<Vouchersetupdetail> Vouchersetupdetails { get; set; }
    }
}