namespace ERP.DataAccess.EntityModels
{
    public partial class Advanceadjustment : IAuditable { }
    public partial class Advanceadjustmentdetail : IAuditable { }
    public partial class Advanceadjustmentattachment : IAuditable { }
    public partial class Aspnetrole : IAuditable { }
    public partial class Aspnetroleclaim : IAuditable { }
    public partial class Aspnetuser : IAuditable { }
    public partial class Aspnetuserclaim : IAuditable { }
    public partial class Aspnetuserlogin : IAuditable { }
    public partial class Aspnetuserrole : IAuditable { }
    public partial class Aspnetusertoken : IAuditable { }
    public partial class Attachment : IAuditable { }
    public partial class Attachmentcategory : IAuditable { }
    public partial class Attachmentstorageaccount : IAuditable { }
    public partial class Chargetype : IAuditable { }
    public partial class City : IAuditable { }
    public partial class Company : IAuditable { }
    public partial class Contravoucher : IAuditable { }
    public partial class Contravoucherdetail : IAuditable { }
    public partial class Contravoucherattachment : IAuditable { }
    public partial class Country : IAuditable { }
    public partial class Creditnote : IAuditable { }
    public partial class Creditnotedetail : IAuditable { }
    public partial class Creditnotedetailtax : IAuditable { }
    public partial class Creditnotetax : IAuditable { }
    public partial class Creditnoteattachment : IAuditable { }
    public partial class Currency : IAuditable { }
    public partial class Currencyconversion : IAuditable { }
    public partial class Debitnote : IAuditable { }
    public partial class Debitnotedetail : IAuditable { }
    public partial class Debitnotedetailtax : IAuditable { }
    public partial class Debitnotetax : IAuditable { }
    public partial class Debitnoteattachment : IAuditable { }
    public partial class Department : IAuditable { }
    public partial class Designation : IAuditable { }
    public partial class Employee : IAuditable { }
    public partial class Financialyear : IAuditable { }
    public partial class Financialyearcompanyrelation : IAuditable { }
    public partial class Form : IAuditable { }
    public partial class Journalvoucher : IAuditable { }
    public partial class Journalvoucherdetail : IAuditable { }
    public partial class Journalvoucherattachment : IAuditable { }
    public partial class Ledger : IAuditable { }
    public partial class Ledgeraddress : IAuditable { }
    public partial class Ledgerattachment : IAuditable { }
    public partial class Ledgercompanyrelation : IAuditable { }
    public partial class Ledgerfinancialyearbalance : IAuditable { }
    public partial class Module : IAuditable { }
    public partial class Paymentvoucher : IAuditable { }
    public partial class Paymentvoucherdetail : IAuditable { }
    public partial class Paymentvoucherattachment : IAuditable { }
    public partial class Purchaseinvoice : IAuditable { }
    public partial class Purchaseinvoicedetail : IAuditable { }
    public partial class Purchaseinvoicedetailtax : IAuditable { }
    public partial class Purchaseinvoicetax : IAuditable { }
    public partial class Purchaseinvoiceattachment : IAuditable { }
    public partial class Receiptvoucher : IAuditable { }
    public partial class Receiptvoucherdetail : IAuditable { }
    public partial class Receiptvoucherattachment : IAuditable { }
    public partial class Salesinvoice : IAuditable { }
    public partial class Salesinvoicedetail : IAuditable { }
    public partial class Salesinvoicedetailtax : IAuditable { }
    public partial class Salesinvoicetax : IAuditable { }
    public partial class Salesinvoiceattachment : IAuditable { }
    public partial class State : IAuditable { }
    public partial class Status : IAuditable { }
    public partial class Taxregister : IAuditable { }
    public partial class Taxregisterdetail : IAuditable { }
    public partial class Unitofmeasurement : IAuditable { }
    public partial class Vouchersetup : IAuditable { }
    public partial class Vouchersetupdetail : IAuditable { }
    public partial class Voucherstyle : IAuditable { }
}
