// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ERP.DataAccess.EntityModels;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using ERP.DataAccess.Entity;

namespace ERP.DataAccess.EntityData
{
    public partial class ErpDbContext : IdentityDbContext<ApplicationIdentityUser, ApplicationRole, int>
    {
        public ErpDbContext()
        {
        }

        public ErpDbContext(DbContextOptions<ErpDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Aspnetrole> Aspnetroles { get; set; }
        public virtual DbSet<Aspnetroleclaim> Aspnetroleclaims { get; set; }
        public virtual DbSet<Aspnetuser> Aspnetusers { get; set; }
        public virtual DbSet<Aspnetuserclaim> Aspnetuserclaims { get; set; }
        public virtual DbSet<Aspnetuserlogin> Aspnetuserlogins { get; set; }
        public virtual DbSet<Aspnetuserrole> Aspnetuserroles { get; set; }
        public virtual DbSet<Aspnetusertoken> Aspnetusertokens { get; set; }
        public virtual DbSet<Chargetype> Chargetypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Currencyconversion> Currencyconversions { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Financialyear> Financialyears { get; set; }
        public virtual DbSet<Financialyearcompanyrelation> Financialyearcompanyrelations { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<Ledgeraddress> Ledgeraddresses { get; set; }
        public virtual DbSet<Ledgercompanyrelation> Ledgercompanyrelations { get; set; }
        public virtual DbSet<Ledgerfinancialyearbalance> Ledgerfinancialyearbalances { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Purchaseinvoice> Purchaseinvoices { get; set; }
        public virtual DbSet<Purchaseinvoicedetail> Purchaseinvoicedetails { get; set; }
        public virtual DbSet<Purchaseinvoicedetailtax> Purchaseinvoicedetailtaxes { get; set; }
        public virtual DbSet<Purchaseinvoicetax> Purchaseinvoicetaxes { get; set; }
        public virtual DbSet<Salesinvoice> Salesinvoices { get; set; }
        public virtual DbSet<Salesinvoicedetail> Salesinvoicedetails { get; set; }
        public virtual DbSet<Salesinvoicedetailtax> Salesinvoicedetailtaxes { get; set; }
        public virtual DbSet<Salesinvoicetax> Salesinvoicetaxes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<Taxregister> Taxregisters { get; set; }
        public virtual DbSet<Taxregisterdetail> Taxregisterdetails { get; set; }
        public virtual DbSet<Unitofmeasurement> Unitofmeasurements { get; set; }
        public virtual DbSet<Vouchersetup> Vouchersetups { get; set; }
        public virtual DbSet<Vouchersetupdetail> Vouchersetupdetails { get; set; }
        public virtual DbSet<Voucherstyle> Voucherstyles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
             base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Aspnetrole>(entity =>
            {
                entity.HasIndex(e => e.NormalizedName)
                    .HasName("RoleNameIndex")
                    .IsUnique();

                entity.Property(e => e.ConcurrencyStamp)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Name)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NormalizedName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");
            });

            modelBuilder.Entity<Aspnetroleclaim>(entity =>
            {
                entity.HasIndex(e => e.RoleId)
                    .HasName("IX_AspNetRoleClaims_RoleId");

                entity.Property(e => e.ClaimType)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.ClaimValue)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.Aspnetroleclaims)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_AspNetRoleClaims_AspNetRoles_RoleId");
            });

            modelBuilder.Entity<Aspnetuser>(entity =>
            {
                entity.HasIndex(e => e.NormalizedEmail)
                    .HasName("EmailIndex");

                entity.HasIndex(e => e.NormalizedUserName)
                    .HasName("UserNameIndex")
                    .IsUnique();

                entity.Property(e => e.ConcurrencyStamp)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Email)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NormalizedEmail)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NormalizedUserName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PasswordHash)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PhoneNumber)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.SecurityStamp)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.UserName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");
            });

            modelBuilder.Entity<Aspnetuserclaim>(entity =>
            {
                entity.HasIndex(e => e.UserId)
                    .HasName("IX_AspNetUserClaims_UserId");

                entity.Property(e => e.ClaimType)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.ClaimValue)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Aspnetuserclaims)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_AspNetUserClaims_AspNetUsers_UserId");
            });

            modelBuilder.Entity<Aspnetuserlogin>(entity =>
            {
                entity.HasKey(e => new { e.LoginProvider, e.ProviderKey })
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                entity.HasIndex(e => e.UserId)
                    .HasName("IX_AspNetUserLogins_UserId");

                entity.Property(e => e.LoginProvider)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.ProviderKey)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.ProviderDisplayName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Aspnetuserlogins)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_AspNetUserLogins_AspNetUsers_UserId");
            });

            modelBuilder.Entity<Aspnetuserrole>(entity =>
            {
                entity.HasKey(e => new { e.UserId, e.RoleId })
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                entity.HasIndex(e => e.RoleId)
                    .HasName("IX_AspNetUserRoles_RoleId");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.Aspnetuserroles)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_AspNetUserRoles_AspNetRoles_RoleId");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Aspnetuserroles)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_AspNetUserRoles_AspNetUsers_UserId");
            });

            modelBuilder.Entity<Aspnetusertoken>(entity =>
            {
                entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name })
                    .HasName("PRIMARY")
                    .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                entity.Property(e => e.LoginProvider)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Name)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Value)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.User)
                    .WithMany(p => p.Aspnetusertokens)
                    .HasForeignKey(d => d.UserId)
                    .HasConstraintName("FK_AspNetUserTokens_AspNetUsers_UserId");
            });

            modelBuilder.Entity<Chargetype>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_ChargeType_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_ChargeType_User_UpdatedByUserId_idx");

                entity.Property(e => e.ChargeTypeName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.ChargetypePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_ChargeType_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.ChargetypeUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_ChargeType_User_UpdatedByUserId");
            });

            modelBuilder.Entity<City>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_City_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.StateId)
                    .HasName("IX_City_StateId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_City_User_UpdatedByUserId_idx");

                entity.Property(e => e.CityName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.CityPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_City_User_PreparedByUserId");

                entity.HasOne(d => d.State)
                    .WithMany(p => p.Cities)
                    .HasForeignKey(d => d.StateId)
                    .HasConstraintName("FK_City_State_StateId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.CityUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_City_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Company>(entity =>
            {
                entity.HasIndex(e => e.CurrencyId)
                    .HasName("IX_Company_CurrencyId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Company_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Company_User_UpdatedByUserId_idx");

                entity.Property(e => e.Address)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.AlternatePhoneNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.CompanyName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.EmailAddress)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.FaxNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PhoneNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PostalCode)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Website)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Currency)
                    .WithMany(p => p.Companies)
                    .HasForeignKey(d => d.CurrencyId)
                    .HasConstraintName("FK_Company_Currency_CurrencyId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.CompanyPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Company_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.CompanyUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Company_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Country>(entity =>
            {
                entity.HasIndex(e => e.CountryName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Country_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Country_User_UpdatedByUserId_idx");

                entity.Property(e => e.CountryName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.CountryPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Country_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.CountryUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Country_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Currency>(entity =>
            {
                entity.HasIndex(e => e.CurrencyName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Currency_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Currency_User_UpdatedByUserId_idx");

                entity.Property(e => e.CurrencyCode)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.CurrencyName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Denomination)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.CurrencyPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Currency_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.CurrencyUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Currency_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Currencyconversion>(entity =>
            {
                entity.HasKey(e => e.ConversionId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_CurrencyConversion_CompanyId");

                entity.HasIndex(e => e.CurrencyId)
                    .HasName("IX_CurrencyConversion_CurrencyId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_CurrencyConversion_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_CurrencyConversion_User_UpdatedByUserId_idx");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Currencyconversions)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_CurrencyConversion_Company_CompanyId");

                entity.HasOne(d => d.Currency)
                    .WithMany(p => p.Currencyconversions)
                    .HasForeignKey(d => d.CurrencyId)
                    .HasConstraintName("FK_CurrencyConversion_Currency_CurrencyId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.CurrencyconversionPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_CurrencyConversion_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.CurrencyconversionUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_CurrencyConversion_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Department>(entity =>
            {
                entity.HasIndex(e => e.DepartmentName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Department_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Department_User_UpdatedByUserId_idx");

                entity.Property(e => e.DepartmentName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.DepartmentPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Department_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.DepartmentUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Department_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Designation>(entity =>
            {
                entity.HasIndex(e => e.DesignationName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Designation_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Designation_User_UpdatedByUserId_idx");

                entity.Property(e => e.DesignationName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.DesignationPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Designation_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.DesignationUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Designation_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.HasIndex(e => e.DepartmentId)
                    .HasName("IX_Employee_DepartmentId");

                entity.HasIndex(e => e.DesignationId)
                    .HasName("IX_Employee_DesignationId");

                entity.HasIndex(e => e.EmployeeCode)
                    .HasName("Code_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Employee_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Employee_User_UpdatedByUserId_idx");

                entity.Property(e => e.EmailAddress)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.EmployeeCode)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.FirstName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.LastName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Department)
                    .WithMany(p => p.Employees)
                    .HasForeignKey(d => d.DepartmentId)
                    .HasConstraintName("FK_Employee_Department_DepartmentId");

                entity.HasOne(d => d.Designation)
                    .WithMany(p => p.Employees)
                    .HasForeignKey(d => d.DesignationId)
                    .HasConstraintName("FK_Employee_Designation_DesignationId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.EmployeePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Employee_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.EmployeeUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Employee_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Financialyear>(entity =>
            {
                entity.HasIndex(e => e.FinancialYearName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_FinancialYear_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_FinancialYear_User_UpdatedByUserId_idx");

                entity.Property(e => e.FinancialYearName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.FinancialyearPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_FinancialYear_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.FinancialyearUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_FinancialYear_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Financialyearcompanyrelation>(entity =>
            {
                entity.HasKey(e => e.RelationId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_FinancialYearCompanyRelation_CompanyId");

                entity.HasIndex(e => e.FinancialYearId)
                    .HasName("IX_FinancialYearCompanyRelation_FinancialYearId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_FinancialYearCompanyRelation_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_FinancialYearCompanyRelation_User_UpdatedByUserId_idx");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Financialyearcompanyrelations)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_FinancialYearCompanyRelation_Company_CompanyId");

                entity.HasOne(d => d.FinancialYear)
                    .WithMany(p => p.Financialyearcompanyrelations)
                    .HasForeignKey(d => d.FinancialYearId)
                    .HasConstraintName("FK_FinancialYearCompanyRelation_FinancialYear_FinancialYearId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.FinancialyearcompanyrelationPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_FinancialYearCompanyRelation_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.FinancialyearcompanyrelationUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_FinancialYearCompanyRelation_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Form>(entity =>
            {
                entity.HasIndex(e => e.FormName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.ModuleId)
                    .HasName("IX_Form_Module_ModuleId_idx");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Form_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Form_User_UpdatedByUserId_idx");

                entity.Property(e => e.FormName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Module)
                    .WithMany(p => p.Forms)
                    .HasForeignKey(d => d.ModuleId)
                    .HasConstraintName("FK_Form_Module_ModuleId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.FormPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Form_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.FormUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Form_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Ledger>(entity =>
            {
                entity.HasIndex(e => e.LedgerCode)
                    .HasName("Code_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.ParentGroupId)
                    .HasName("IX_Ledger_ParentGroupId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Ledger_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Ledger_User_UpdatedByUserId_idx");

                entity.Property(e => e.LedgerCode)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.LedgerName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxRegisteredNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.ParentGroup)
                    .WithMany(p => p.InverseParentGroup)
                    .HasForeignKey(d => d.ParentGroupId)
                    .HasConstraintName("FK_Ledger_Ledger_ParentGroupId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.LedgerPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Ledger_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.LedgerUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Ledger_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Ledgeraddress>(entity =>
            {
                entity.HasKey(e => e.AddressId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CityId)
                    .HasName("IX_LedgerAddress_CityId");

                entity.HasIndex(e => e.CountryId)
                    .HasName("IX_LedgerAddress_CountryId");

                entity.HasIndex(e => e.LedgerId)
                    .HasName("IX_LedgerAddress_LedgerId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_LedgerAddress_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.StateId)
                    .HasName("IX_LedgerAddress_StateId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_LedgerAddress_User_UpdatedByUserId_idx");

                entity.Property(e => e.AddressDescription)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.EmailAddress)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.FaxNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PhoneNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PostalCode)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.City)
                    .WithMany(p => p.Ledgeraddresses)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_LedgerAddress_City_CityId");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.Ledgeraddresses)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_LedgerAddress_Country_CountryId");

                entity.HasOne(d => d.Ledger)
                    .WithMany(p => p.Ledgeraddresses)
                    .HasForeignKey(d => d.LedgerId)
                    .HasConstraintName("FK_LedgerAddress_Ledger_LedgerId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.LedgeraddressPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_LedgerAddress_User_PreparedByUserId");

                entity.HasOne(d => d.State)
                    .WithMany(p => p.Ledgeraddresses)
                    .HasForeignKey(d => d.StateId)
                    .HasConstraintName("FK_LedgerAddress_State_StateId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.LedgeraddressUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_LedgerAddress_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Ledgercompanyrelation>(entity =>
            {
                entity.HasKey(e => e.RelationId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_LedgerCompanyRelation_CompanyId");

                entity.HasIndex(e => e.LedgerId)
                    .HasName("IX_LedgerCompanyRelation_LedgerId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_LedgerCompanyRelation_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_LedgerCompanyRelation_User_UpdatedByUserId_idx");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Ledgercompanyrelations)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_LedgerCompanyRelation_Company_CompanyId");

                entity.HasOne(d => d.Ledger)
                    .WithMany(p => p.Ledgercompanyrelations)
                    .HasForeignKey(d => d.LedgerId)
                    .HasConstraintName("FK_LedgerCompanyRelation_Ledger_LedgerId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.LedgercompanyrelationPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_LedgerCompanyRelation_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.LedgercompanyrelationUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_LedgerCompanyRelation_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Ledgerfinancialyearbalance>(entity =>
            {
                entity.HasKey(e => e.LedgerBalanceId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_LedgerFinancialYearBalance_CompanyId");

                entity.HasIndex(e => e.CurrencyId)
                    .HasName("IX_LedgerFinancialYearBalance_CurrencyId");

                entity.HasIndex(e => e.FinancialYearId)
                    .HasName("IX_LedgerFinancialYearBalance_FinancialYearId");

                entity.HasIndex(e => e.LedgerId)
                    .HasName("IX_LedgerFinancialYearBalance_LedgerId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_LedgerFinancialYearBalance_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_LedgerFinancialYearBalance_User_UpdatedByUserId_idx");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Ledgerfinancialyearbalances)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_Company_CompanyId");

                entity.HasOne(d => d.Currency)
                    .WithMany(p => p.Ledgerfinancialyearbalances)
                    .HasForeignKey(d => d.CurrencyId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_Currency_CurrencyId");

                entity.HasOne(d => d.FinancialYear)
                    .WithMany(p => p.Ledgerfinancialyearbalances)
                    .HasForeignKey(d => d.FinancialYearId)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_FinancialYear_FinancialYearId");

                entity.HasOne(d => d.Ledger)
                    .WithMany(p => p.Ledgerfinancialyearbalances)
                    .HasForeignKey(d => d.LedgerId)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_Ledger_LedgerId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.LedgerfinancialyearbalancePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.LedgerfinancialyearbalanceUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_LedgerFinancialYearBalance_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Module>(entity =>
            {
                entity.HasIndex(e => e.ModuleName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Module_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Module_User_UpdatedByUserId_idx");

                entity.Property(e => e.ModuleName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.ModulePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Module_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.ModuleUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Module_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Purchaseinvoice>(entity =>
            {
                entity.HasIndex(e => e.AccountLedgerId)
                    .HasName("IX_PurchaseInvoice_AccountLedgerId");

                entity.HasIndex(e => e.BillToAddressId)
                    .HasName("FK_PurchaseInvoice_Ledger_BillToAddressId_idx");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_PurchaseInvoice_CompanyId");

                entity.HasIndex(e => e.CurrencyId)
                    .HasName("IX_PurchaseInvoice_CurrencyId");

                entity.HasIndex(e => e.FinancialYearId)
                    .HasName("IX_PurchaseInvoice_FinancialYearId");

                entity.HasIndex(e => e.InvoiceNo)
                    .HasName("DocumentNo_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_PurchaseInvoice_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.StatusId)
                    .HasName("IX_PurchaseInvoice_StatusId");

                entity.HasIndex(e => e.SupplierLedgerId)
                    .HasName("IX_PurchaseInvoice_SupplierLedgerId");

                entity.HasIndex(e => e.TaxRegisterId)
                    .HasName("IX_PurchaseInvoice_TaxRegisterId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_PurchaseInvoice_User_UpdatedByUserId_idx");

                entity.HasIndex(e => e.VoucherStyleId)
                    .HasName("tf_idx");

                entity.Property(e => e.DiscountPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.InvoiceNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NetAmountFcinWord)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PaymentTerm)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.SupplierReferenceNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxModelType)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.AccountLedger)
                    .WithMany(p => p.PurchaseinvoiceAccountLedgers)
                    .HasForeignKey(d => d.AccountLedgerId)
                    .HasConstraintName("FK_PurchaseInvoice_Ledger_AccountLedgerId");

                entity.HasOne(d => d.BillToAddress)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.BillToAddressId)
                    .HasConstraintName("FK_PurchaseInvoice_Ledger_BillToAddressId");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_PurchaseInvoice_Company_CompanyId");

                entity.HasOne(d => d.Currency)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.CurrencyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PurchaseInvoice_Currency_CurrencyId");

                entity.HasOne(d => d.FinancialYear)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.FinancialYearId)
                    .HasConstraintName("FK_PurchaseInvoice_FinancialYear_FinancialYearId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.PurchaseinvoicePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_PurchaseInvoice_User_PreparedByUserId");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.StatusId)
                    .HasConstraintName("FK_PurchaseInvoice_Status_StatusId");

                entity.HasOne(d => d.SupplierLedger)
                    .WithMany(p => p.PurchaseinvoiceSupplierLedgers)
                    .HasForeignKey(d => d.SupplierLedgerId)
                    .HasConstraintName("FK_PurchaseInvoice_Ledger_SupplierLedgerId");

                entity.HasOne(d => d.TaxRegister)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.TaxRegisterId)
                    .HasConstraintName("FK_PurchaseInvoice_TaxRegister_TaxRegisterId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.PurchaseinvoiceUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_PurchaseInvoice_User_UpdatedByUserId");

                entity.HasOne(d => d.VoucherStyle)
                    .WithMany(p => p.Purchaseinvoices)
                    .HasForeignKey(d => d.VoucherStyleId)
                    .HasConstraintName("FK_PurchaseInvoice_VoucherStyle_VoucherStyleId");
            });

            modelBuilder.Entity<Purchaseinvoicedetail>(entity =>
            {
                entity.HasKey(e => e.PurchaseInvoiceDetId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_PurchaseInvoiceDetails_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.PurchaseInvoiceId)
                    .HasName("IX_PurchaseInvoiceDetails_PurchaseInvoiceId");

                entity.HasIndex(e => e.UnitOfMeasurementId)
                    .HasName("IX_PurchaseInvoiceDetails_UnitOfMeasurementId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_PurchaseInvoiceDetails_User_UpdatedByUserId_idx");

                entity.Property(e => e.Description)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.PurchaseinvoicedetailPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceDetails_User_PreparedByUserId");

                entity.HasOne(d => d.PurchaseInvoice)
                    .WithMany(p => p.Purchaseinvoicedetails)
                    .HasForeignKey(d => d.PurchaseInvoiceId)
                    .HasConstraintName("FK_PurchaseInvoiceDetails_PurchaseInvoice_PurchaseInvoiceId");

                entity.HasOne(d => d.UnitOfMeasurement)
                    .WithMany(p => p.Purchaseinvoicedetails)
                    .HasForeignKey(d => d.UnitOfMeasurementId)
                    .HasConstraintName("FK_PurchaseInvoiceDetails_UnitOfMeasurement_UnitOfMeasurementId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.PurchaseinvoicedetailUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceDetails_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Purchaseinvoicedetailtax>(entity =>
            {
                entity.HasKey(e => e.PurchaseInvoiceDetTaxId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_PurchaseInvoiceDetailTax_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.PurchaseInvoiceDetId)
                    .HasName("IX_PurchaseInvoiceDetailTax_PurchaseInvoiceDetId");

                entity.HasIndex(e => e.TaxLedgerId)
                    .HasName("IX_PurchaseInvoiceDetailTax_TaxLedgerId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_PurchaseInvoiceDetailTax_User_UpdatedByUserId_idx");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxAddOrDeduct)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.PurchaseinvoicedetailtaxPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceDetailTax_User_PreparedByUserId");

                entity.HasOne(d => d.PurchaseInvoiceDet)
                    .WithMany(p => p.Purchaseinvoicedetailtaxes)
                    .HasForeignKey(d => d.PurchaseInvoiceDetId)
                    .HasConstraintName("FK_PIDetailTax_InvoiceDetail_PurchaseInvoiceDetId");

                entity.HasOne(d => d.TaxLedger)
                    .WithMany(p => p.Purchaseinvoicedetailtaxes)
                    .HasForeignKey(d => d.TaxLedgerId)
                    .HasConstraintName("FK_PurchaseInvoiceDetailTax_Ledger_TaxLedgerId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.PurchaseinvoicedetailtaxUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceDetailTax_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Purchaseinvoicetax>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_PurchaseInvoiceTax_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.PurchaseInvoiceId)
                    .HasName("IX_PurchaseInvoiceTax_PurchaseInvoiceId");

                entity.HasIndex(e => e.TaxLedgerId)
                    .HasName("IX_PurchaseInvoiceTax_TaxLedgerId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_PurchaseInvoiceTax_User_UpdatedByUserId_idx");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxAddOrDeduct)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.PurchaseinvoicetaxPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceTax_User_PreparedByUserId");

                entity.HasOne(d => d.PurchaseInvoice)
                    .WithMany(p => p.Purchaseinvoicetaxes)
                    .HasForeignKey(d => d.PurchaseInvoiceId)
                    .HasConstraintName("FK_PurchaseInvoiceTax_PurchaseInvoice_PurchaseInvoiceId");

                entity.HasOne(d => d.TaxLedger)
                    .WithMany(p => p.Purchaseinvoicetaxes)
                    .HasForeignKey(d => d.TaxLedgerId)
                    .HasConstraintName("FK_PurchaseInvoiceTax_Ledger_TaxLedgerId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.PurchaseinvoicetaxUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_PurchaseInvoiceTax_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Salesinvoice>(entity =>
            {
                entity.HasKey(e => e.InvoiceId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.AccountLedgerId)
                    .HasName("IX_SalesInvoice_AccountLedgerId");

                entity.HasIndex(e => e.BankLedgerId)
                    .HasName("IX_SalesInvoice_BankLedgerId");

                entity.HasIndex(e => e.BillToAddressId)
                    .HasName("FK_SalesInvoice_Ledger_BillToAddressId_idx");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_SalesInvoice_CompanyId");

                entity.HasIndex(e => e.CurrencyId)
                    .HasName("IX_SalesInvoice_CurrencyId");

                entity.HasIndex(e => e.CustomerLedgerId)
                    .HasName("IX_SalesInvoice_CustomerLedgerId");

                entity.HasIndex(e => e.FinancialYearId)
                    .HasName("IX_SalesInvoice_FinancialYearId");

                entity.HasIndex(e => e.InvoiceNo)
                    .HasName("DocumentNo_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_SalesInvoice_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.StatusId)
                    .HasName("IX_SalesInvoice_StatusId");

                entity.HasIndex(e => e.TaxRegisterId)
                    .HasName("IX_SalesInvoice_TaxRegisterId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_SalesInvoice_User_UpdatedByUserId_idx");

                entity.HasIndex(e => e.VoucherStyleId)
                    .HasName("IX_SalesInvoice_VoucherStyle_VoucherStyleId_idx");

                entity.Property(e => e.CustomerReferenceNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.DiscountPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.InvoiceNo)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NetAmountFcinWord)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.PaymentTerm)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxModelType)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.AccountLedger)
                    .WithMany(p => p.SalesinvoiceAccountLedgers)
                    .HasForeignKey(d => d.AccountLedgerId)
                    .HasConstraintName("FK_SalesInvoice_Ledger_AccountLedgerId");

                entity.HasOne(d => d.BankLedger)
                    .WithMany(p => p.SalesinvoiceBankLedgers)
                    .HasForeignKey(d => d.BankLedgerId)
                    .HasConstraintName("FK_SalesInvoice_Ledger_BankLedgerId");

                entity.HasOne(d => d.BillToAddress)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.BillToAddressId)
                    .HasConstraintName("FK_SalesInvoice_Ledger_BillToAddressId");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_SalesInvoice_Company_CompanyId");

                entity.HasOne(d => d.Currency)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.CurrencyId)
                    .HasConstraintName("FK_SalesInvoice_Currency_CurrencyId");

                entity.HasOne(d => d.CustomerLedger)
                    .WithMany(p => p.SalesinvoiceCustomerLedgers)
                    .HasForeignKey(d => d.CustomerLedgerId)
                    .HasConstraintName("FK_SalesInvoice_Ledger_CustomerLedgerId");

                entity.HasOne(d => d.FinancialYear)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.FinancialYearId)
                    .HasConstraintName("FK_SalesInvoice_FinancialYear_FinancialYearId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.SalesinvoicePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_SalesInvoice_User_PreparedByUserId");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.StatusId)
                    .HasConstraintName("FK_SalesInvoice_Status_StatusId");

                entity.HasOne(d => d.TaxRegister)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.TaxRegisterId)
                    .HasConstraintName("FK_SalesInvoice_TaxRegister_TaxRegisterId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.SalesinvoiceUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_SalesInvoice_User_UpdatedByUserId");

                entity.HasOne(d => d.VoucherStyle)
                    .WithMany(p => p.Salesinvoices)
                    .HasForeignKey(d => d.VoucherStyleId)
                    .HasConstraintName("FK_SalesInvoice_VoucherStyle_VoucherStyleId");
            });

            modelBuilder.Entity<Salesinvoicedetail>(entity =>
            {
                entity.HasKey(e => e.InvoiceDetId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.InvoiceId)
                    .HasName("IX_SalesInvoiceDetails_InvoiceId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_SalesInvoiceDetails_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UnitOfMeasurementId)
                    .HasName("IX_SalesInvoiceDetails_UnitOfMeasurementId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_SalesInvoiceDetails_User_UpdatedByUserId_idx");

                entity.Property(e => e.Description)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxAmount).HasDefaultValueSql("'0.0000'");

                entity.Property(e => e.TaxAmountFc).HasDefaultValueSql("'0.0000'");

                entity.HasOne(d => d.Invoice)
                    .WithMany(p => p.Salesinvoicedetails)
                    .HasForeignKey(d => d.InvoiceId)
                    .HasConstraintName("FK_SalesInvoiceDetails_SalesInvoice_InvoiceId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.SalesinvoicedetailPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_SalesInvoiceDetails_User_PreparedByUserId");

                entity.HasOne(d => d.UnitOfMeasurement)
                    .WithMany(p => p.Salesinvoicedetails)
                    .HasForeignKey(d => d.UnitOfMeasurementId)
                    .HasConstraintName("FK_SalesInvoiceDetails_UnitOfMeasurement_UnitOfMeasurementId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.SalesinvoicedetailUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_SalesInvoiceDetails_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Salesinvoicedetailtax>(entity =>
            {
                entity.HasKey(e => e.InvoiceDetTaxId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.InvoiceDetId)
                    .HasName("IX_SalesInvoiceDetailsTax_InvoiceDetId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_SalesInvoiceDetailsTax_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.TaxLedgerId)
                    .HasName("IX_SalesInvoiceDetailsTax_TaxLedgerId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_SalesInvoiceDetailsTax_User_UpdatedByUserId_idx");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxAddOrDeduct)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.InvoiceDet)
                    .WithMany(p => p.Salesinvoicedetailtaxes)
                    .HasForeignKey(d => d.InvoiceDetId)
                    .HasConstraintName("FK_SalesInvoiceDetailsTax_SalesInvoiceDetails_InvoiceDetId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.SalesinvoicedetailtaxPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_SalesInvoiceDetailsTax_User_PreparedByUserId");

                entity.HasOne(d => d.TaxLedger)
                    .WithMany(p => p.Salesinvoicedetailtaxes)
                    .HasForeignKey(d => d.TaxLedgerId)
                    .HasConstraintName("FK_SalesInvoiceDetailsTax_Ledger_TaxLedgerId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.SalesinvoicedetailtaxUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_SalesInvoiceDetailsTax_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Salesinvoicetax>(entity =>
            {
                entity.HasKey(e => e.InvoiceTaxId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.InvoiceId)
                    .HasName("IX_SalesInvoiceTax_InvoiceId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_SalesInvoiceTax_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.TaxLedgerId)
                    .HasName("IX_SalesInvoiceTax_TaxLedgerId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_SalesInvoiceTax_User_UpdatedByUserId_idx");

                entity.Property(e => e.Remark)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxAddOrDeduct)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Invoice)
                    .WithMany(p => p.Salesinvoicetaxes)
                    .HasForeignKey(d => d.InvoiceId)
                    .HasConstraintName("FK_SalesInvoiceTax_SalesInvoice_InvoiceId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.SalesinvoicetaxPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_SalesInvoiceTax_User_PreparedByUserId");

                entity.HasOne(d => d.TaxLedger)
                    .WithMany(p => p.Salesinvoicetaxes)
                    .HasForeignKey(d => d.TaxLedgerId)
                    .HasConstraintName("FK_SalesInvoiceTax_Ledger_TaxLedgerId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.SalesinvoicetaxUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_SalesInvoiceTax_User_UpdatedByUserId");
            });

            modelBuilder.Entity<State>(entity =>
            {
                entity.HasIndex(e => e.CountryId)
                    .HasName("IX_State_CountryId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_State_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_State_User_UpdatedByUserId_idx");

                entity.Property(e => e.StateName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.States)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK_State_Country_CountryId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.StatePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_State_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.StateUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_State_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Status>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_Status_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.StatusName)
                    .HasName("Description_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_Status_User_UpdatedByUserId_idx");

                entity.Property(e => e.StatusName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.StatusPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_Status_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.StatusUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_Status_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Taxregister>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_TaxRegister_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.TaxRegisterName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_TaxRegister_User_UpdatedByUserId_idx");

                entity.Property(e => e.TaxRegisterName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.TaxregisterPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_TaxRegister_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.TaxregisterUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_TaxRegister_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Taxregisterdetail>(entity =>
            {
                entity.HasKey(e => e.TaxRegisterDetId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_TaxRegisterDetails_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.TaxLedgerId)
                    .HasName("IX_TaxRegisterDetails_TaxLedgerId");

                entity.HasIndex(e => e.TaxRegisterId)
                    .HasName("IX_TaxRegisterDetails_TaxRegisterId");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_TaxRegisterDetails_User_UpdatedByUserId_idx");

                entity.Property(e => e.TaxAddOrDeduct)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.TaxPercentageOrAmount)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.TaxregisterdetailPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_TaxRegisterDetails_User_PreparedByUserId");

                entity.HasOne(d => d.TaxLedger)
                    .WithMany(p => p.Taxregisterdetails)
                    .HasForeignKey(d => d.TaxLedgerId)
                    .HasConstraintName("FK_TaxRegisterDetails_Ledger_TaxLedgerId");

                entity.HasOne(d => d.TaxRegister)
                    .WithMany(p => p.Taxregisterdetails)
                    .HasForeignKey(d => d.TaxRegisterId)
                    .HasConstraintName("FK_TaxRegisterDetails_TaxRegister_TaxRegisterId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.TaxregisterdetailUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_TaxRegisterDetails_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Unitofmeasurement>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_UnitOfMeasurement_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UnitOfMeasurementName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_UnitOfMeasurement_User_UpdatedByUserId_idx");

                entity.Property(e => e.UnitOfMeasurementName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.UnitofmeasurementPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_UnitOfMeasurement_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.UnitofmeasurementUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_UnitOfMeasurement_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Vouchersetup>(entity =>
            {
                entity.HasIndex(e => e.ModuleId)
                    .HasName("IX_VoucherSetup_Module_ModuleId_idx");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_VoucherSetup_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_VoucherSetup_User_UpdatedByUserId_idx");

                entity.HasIndex(e => e.VoucherSetupName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.Property(e => e.VoucherSetupName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Module)
                    .WithMany(p => p.Vouchersetups)
                    .HasForeignKey(d => d.ModuleId)
                    .HasConstraintName("FK_VoucherSetup_Module_ModuleId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.VouchersetupPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_VoucherSetup_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.VouchersetupUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_VoucherSetup_User_UpdatedByUserId");
            });

            modelBuilder.Entity<Vouchersetupdetail>(entity =>
            {
                entity.HasKey(e => e.VoucherSetupDetId)
                    .HasName("PRIMARY");

                entity.HasIndex(e => e.CompanyId)
                    .HasName("IX_VoucherSetupDetails_Company_CompanyId");

                entity.HasIndex(e => e.FinancialYearId)
                    .HasName("IX_VoucherSetupDetails_FinancialYear_FinancialYearId");

                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_VoucherSetupDetails_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_VoucherSetupDetails_User_UpdatedByUserId_idx");

                entity.HasIndex(e => e.VoucherSetupId)
                    .HasName("IX_VoucherSetupDetails_VoucherSetup_VoucherSetupId");

                entity.HasIndex(e => e.VoucherStyleId)
                    .HasName("IX_VoucherSetupDetails_VoucherStyle_VoucherStyleId");

                entity.Property(e => e.FormatText)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NoPad)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NoPostString)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NoPreString)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.Property(e => e.NoSeparator)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.Company)
                    .WithMany(p => p.Vouchersetupdetails)
                    .HasForeignKey(d => d.CompanyId)
                    .HasConstraintName("FK_VoucherSetupDetails_Company_CompanyId");

                entity.HasOne(d => d.FinancialYear)
                    .WithMany(p => p.Vouchersetupdetails)
                    .HasForeignKey(d => d.FinancialYearId)
                    .HasConstraintName("FK_VoucherSetupDetails_FinancialYear_FinancialYearId");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.VouchersetupdetailPreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_VoucherSetupDetails_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.VouchersetupdetailUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_VoucherSetupDetails_User_UpdatedByUserId");

                entity.HasOne(d => d.VoucherSetup)
                    .WithMany(p => p.Vouchersetupdetails)
                    .HasForeignKey(d => d.VoucherSetupId)
                    .HasConstraintName("FK_VoucherSetupDetails_VoucherSetup_VoucherSetupId");

                entity.HasOne(d => d.VoucherStyle)
                    .WithMany(p => p.Vouchersetupdetails)
                    .HasForeignKey(d => d.VoucherStyleId)
                    .HasConstraintName("FK_VoucherSetupDetails_VoucherStyle_VoucherStyleId");
            });

            modelBuilder.Entity<Voucherstyle>(entity =>
            {
                entity.HasIndex(e => e.PreparedByUserId)
                    .HasName("FK_VoucherStyle_User_PreparedByUserId_idx");

                entity.HasIndex(e => e.UpdatedByUserId)
                    .HasName("FK_VoucherStyle_User_UpdatedByUserId_idx");

                entity.HasIndex(e => e.VoucherStyleName)
                    .HasName("Name_UNIQUE")
                    .IsUnique();

                entity.Property(e => e.VoucherStyleName)
                    .HasCharSet("utf8mb4")
                    .HasCollation("utf8mb4_0900_ai_ci");

                entity.HasOne(d => d.PreparedByUser)
                    .WithMany(p => p.VoucherstylePreparedByUsers)
                    .HasForeignKey(d => d.PreparedByUserId)
                    .HasConstraintName("FK_VoucherStyle_User_PreparedByUserId");

                entity.HasOne(d => d.UpdatedByUser)
                    .WithMany(p => p.VoucherstyleUpdatedByUsers)
                    .HasForeignKey(d => d.UpdatedByUserId)
                    .HasConstraintName("FK_VoucherStyle_User_UpdatedByUserId");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}